supabase/supabase-flutter

README.md
Document.
Fixes #23 
No changes the behaviour. Just fix the document.
This fix is really tiny change.
If you'd like to modify the document yourself, please don't hesitate to discard this PR.
I appreciate you to provide such the fantastic BaaS and Packages!!
=> email authentication example code has small mistake.

CHANGELOG.md, pubspec.lock, pubspec.yaml
=> chore: publish version 0.2.8

lib/src/local_storage.dart, lib/src/supabase.dart, lib/src/supabase_auth.dart, lib/src/supabase_auth_required_state.dart, lib/src/supabase_auth_state.dart, lib/src/supabase_deep_linking_mixin.dart, pubspec.lock, pubspec.yaml, test/supabase_flutter_test.dart, test/widget_test_stubs.dart
* Fix typo.
* Update hive for optimizations
* Update supabase for OIDC auth
* Update url_launcher for optimizations
Also, this new version of Hive has added a flush method to help with memory leaks. It shouldn't be run after every write due to performance issues. But we should eventually put a counter so that after X writes we flush.
=> chore: update packages

CHANGELOG.md, pubspec.lock, pubspec.yaml
@bdlukaa 
@dshukertjr 
This fixes the export issue for `OpenIDConnectCredentials`
=> chore: publish 0.3.0

.github/workflows/ci.yml, lib/src/supabase_auth_required_state.dart, pubspec.yaml
If we're going to be using new flutter versions then we need to update our constraints.
We should also not be using the latest stable version of Flutter for our tests. They should be a specific version that is within our constraints.
I was dealing with weird issues for a while.
Fixes:
#112 
#114 
@dshukertjr
=> Update constraints and packages

.github/workflows/ci.yml, analysis_options.yaml, lib/src/supabase_auth_required_state.dart, pubspec.yaml, test/supabase_flutter_test.dart
Currently, only a single version of Flutter is being tested, which causes insufficient test coverage like [this](https://github.com/supabase-community/supabase-flutter/issues/114#issuecomment-1127017982) issue. 
This PR aims to prevent this by testing multiple versions of Flutter in CI.
=> chore: updated ci yaml file to test multiple versions of Flutter

lib/src/supabase.dart, test/supabase_flutter_test.dart
This allows the client to be re-initialized by removing the final.
close #65
=> fix: re-initialize client

CHANGELOG.md, lib/src/supabase_auth.dart, pubspec.yaml
=> fix: update to supabase 1.0.0-dev.3

CHANGELOG.md, lib/src/supabase_auth.dart, lib/src/version.dart, pubspec.yaml
Requires supabase-community/supabase-dart/pull/132 to be merged
=> upgrade supabase 

README.md
=> Documentation about encryption

lib/src/supabase_auth.dart
Fixes https://github.com/supabase-community/supabase-flutter/issues/138
=> Fix WidgetsBinding warning

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
I have also included the underlying changes from supabase-dart and supabase-realtime so that the users of this package don't have to go into the sub libraries to view the updates, but what do you all think about this? Is it good, or is it too much?
=> publish v1.0.0-dev.6

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
fixes https://github.com/supabase-community/supabase-flutter/issues/221
fixes https://github.com/supabase-community/supabase-flutter/issues/215
fixes https://github.com/supabase-community/supabase-flutter/issues/225
=> publish v1.0.0-dev.9

.github/workflows/ci.yml, example/lib/main.dart, example/pubspec.yaml, lib/src/supabase.dart, lib/src/supabase_auth.dart, pubspec.yaml, test/supabase_flutter_test.dart, test/widget_test_stubs.dart
- Upgrade supabase to v1.0.0
- Update the minimum supported Dart to 2.15.0 and  Flutter to 2.8.0
- Modify github actions to test the library against the above versions of Flutter
=> BREAKING: upgrade supabase to v1.0.0

lib/src/supabase.dart, pubspec.yaml
- Adds `storageRetryAttempts`. 
- Adds some docs.
=> feat: add storageretryAttempts to `initialize()`

README.md
Updated links from .io > .com and added links to Flutter tutorials.
=> Internal linking.

README.md
Cleanup and fix up of examples on Readme.
=> minor fix on readme

README.md
Fixes a minor typo in the readme, `ANNON` => `ANON`
Behaviour doesn't change.
Behaviour doesn't change.
=> fix: Minor typo in README

README.md
- update sample code
- reorder sample code
- update links
=> update readme with better code samples

lib/src/supabase_auth.dart
fixes https://github.com/supabase/supabase-flutter/issues/332
=> fix: only start deep link observer on supported platforms

CHANGELOG.md, README.md, lib/src/version.dart, pubspec.yaml
I think the readme can be more cleaned up so that the code samples is closer to the top. This PR strips down some information that might not need to be on the readme file.
=> Clean up of the readme.md file and publish v1.3.1

example/macos/Flutter/GeneratedPluginRegistrant.swift, example/windows/flutter/generated_plugin_registrant.cc, example/windows/flutter/generated_plugins.cmake
Updates the example to the auto generated changes on running `flutter pub get`.
=> refactor: update example

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
I thought of waiting for other PRs, but it might take some time, so wanted to just get this one out
Includes the following:
- fix: show web support on pub.dev [#373](https://github.com/supabase/supabase-flutter/pull/373)
- refactor: update example [#374](https://github.com/supabase/supabase-flutter/pull/374)
=> chore: publish v1.4.2

lib/src/supabase_auth.dart, pubspec.yaml
- Update minimum required Dart version to 2.17.0 and Flutter version to 3.0.0.
- Update webview_flutter to ^4.0.0
fixes https://github.com/supabase/supabase-flutter/issues/423
=> fix: upgrade webview_flutter to 4.0.0

CHANGELOG.md, README.md, lib/src/version.dart, pubspec.yaml
Adds additional instructions to add the bundle ID in the Supabase dashboard on the readme.md.
=> chore: publish v1.7.0 and minor edit on readme

packages/functions_client/pubspec.yaml, packages/gotrue/pubspec.yaml, packages/postgrest/pubspec.yaml, packages/realtime_client/pubspec.yaml, packages/storage_client/pubspec.yaml, packages/supabase/pubspec.yaml, packages/supabase_flutter/pubspec.yaml, packages/yet_another_json_isolate/pubspec.yaml
updates the dependency constraints to sdk < 4.0.0 to make them compatible with Dart 3.X.
=> feat: update dependency constraints to sdk < 4.0.0

packages/supabase/lib/src/supabase_client.dart
=> refactor(supabase): simplify functions url

CHANGELOG.md, packages/gotrue/CHANGELOG.md, packages/gotrue/lib/src/version.dart, packages/gotrue/pubspec.yaml, packages/storage_client/CHANGELOG.md, packages/storage_client/lib/src/version.dart, packages/storage_client/pubspec.yaml, packages/supabase/CHANGELOG.md, packages/supabase/lib/src/version.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/CHANGELOG.md, packages/supabase_flutter/lib/src/version.dart, packages/supabase_flutter/pubspec.yaml
- gotrue@1.8.2
- storage_client@1.5.0
- supabase@1.9.2
- supabase_flutter@1.10.2
=> chore(release): publish packages

packages/gotrue/lib/src/gotrue_client.dart
Implementation of https://github.com/supabase/gotrue-js/pull/698 on Flutter SDK.
=> fix(gotrue): only remove session in otp verification if it's not email change or phone change

packages/supabase_flutter/README.md
The sample code for native Google sign in was missing a few things. This PR adds them.
=> fix(supabase_flutter): update README.md with additional imports and code to enable Google sign in

packages/supabase/lib/src/realtime_client_options.dart
Not well documented.
Comment/comment documentation 
From what I can tell it's automatically 10 per second server-side
=> Events per second comment

packages/gotrue/lib/gotrue.dart, packages/gotrue/lib/src/gotrue_admin_api.dart
- export `SignOutScope` in gotrue
close #575
=> fix(gotrue): export SignOutScope

packages/postgrest/test/reset_helper.dart
Coming from the strangely failing tests in #580, the test didn't succeed somehow. I don't know why the previous prs had no issues with the tests. 
I tried to find the reason. When deleting the `users` table and right after inserting them in the reset helper, the order of the newly inserted users isn't correct. This only happens right before/at the resource embedding tests.
I fixed it now by catching this case and adding a delay. I'm not always using a delay to increase test performance.
=> test(postgrest): properly reset database

.github/workflows/functions_client_ci.yml, .github/workflows/gotrue_ci.yml, .github/workflows/postgrest_ci.yml, .github/workflows/realtime_client_ci.yml, .github/workflows/storage_client_ci.yml, .github/workflows/supabase_ci.yml, .github/workflows/supabase_flutter_ci.yml, .github/workflows/yet_another_json_isolate_ci.yml, packages/functions_client/pubspec.yaml, packages/gotrue/pubspec.yaml, packages/gotrue/test/admin_test.dart, packages/gotrue/test/client_test.dart, packages/gotrue/test/provider_test.dart, packages/gotrue/test/src/gotrue_admin_mfa_api_test.dart, packages/gotrue/test/src/gotrue_mfa_api_test.dart, packages/gotrue/test/utils.dart, packages/postgrest/lib/src/postgrest_query_builder.dart, packages/postgrest/pubspec.yaml, packages/realtime_client/pubspec.yaml, packages/storage_client/lib/src/storage_file_api.dart, packages/storage_client/pubspec.yaml, packages/supabase/pubspec.yaml, packages/supabase/test/utils.dart, packages/supabase_flutter/analysis_options.yaml, packages/supabase_flutter/lib/src/supabase_auth.dart, packages/supabase_flutter/pubspec.yaml, packages/supabase_flutter/test/widget_test_stubs.dart, packages/yet_another_json_isolate/pubspec.yaml, pubspec.lock, pubspec.yaml
This is the first pr to begin working on v2 of our packages.
Where do we want to merge this into? Do we create a new v2 branch and collect all prs there and keep main for v1 or do we do it the other way around?
I would keep the possibility to do fixes to v1 while working on v2.
- Make Dart 3 minimum version
- upgrade lints packages
- fix new linter warnings
- upgrade mocktail in realtime_client
- upgrade dotenv in gotrue
=> refactor!: use Dart 3

packages/gotrue/lib/src/constants.dart, packages/gotrue/lib/src/gotrue_client.dart
Adds WhatsApp support for OTP login
JS implementation are the following:
- https://github.com/supabase/gotrue-js/pull/616
- https://github.com/supabase/gotrue-js/pull/647
=> feat(gotrue): add WhatsApp support for OTP login

packages/gotrue/lib/src/gotrue_client.dart, packages/gotrue/lib/src/types/session.dart, packages/gotrue/test/client_test.dart, packages/gotrue/test/utils.dart, packages/supabase/test/client_test.dart, packages/supabase/test/utils.dart, packages/supabase_flutter/lib/src/local_storage.dart, packages/supabase_flutter/lib/src/local_storage_stub.dart, packages/supabase_flutter/lib/src/local_storage_web.dart, packages/supabase_flutter/lib/src/supabase.dart, packages/supabase_flutter/lib/src/supabase_auth.dart, packages/supabase_flutter/pubspec.yaml, packages/supabase_flutter/test/utils.dart, packages/supabase_flutter/test/widget_test.dart, packages/supabase_flutter/test/widget_test_stubs.dart
Switches from [Hive](https://pub.dev/packages/hive) to [Shared Preferences](https://pub.dev/packages/shared_preferences) for storing the access token
This is done by still including the Hive package:
1. reading the access token
2. writing it to shared prefs
3. removing it from Hive
4. Removing the file and the parent directory
=> feat(supabase_flutter): use SharedPreferences for access token

CHANGELOG.md, melos.yaml, packages/functions_client/CHANGELOG.md, packages/functions_client/lib/src/version.dart, packages/functions_client/pubspec.yaml, packages/gotrue/CHANGELOG.md, packages/gotrue/lib/src/version.dart, packages/gotrue/pubspec.yaml, packages/postgrest/CHANGELOG.md, packages/postgrest/lib/src/version.dart, packages/postgrest/pubspec.yaml, packages/realtime_client/CHANGELOG.md, packages/realtime_client/lib/src/version.dart, packages/realtime_client/pubspec.yaml, packages/storage_client/CHANGELOG.md, packages/storage_client/lib/src/version.dart, packages/storage_client/pubspec.yaml, packages/supabase/CHANGELOG.md, packages/supabase/lib/src/version.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/CHANGELOG.md, packages/supabase_flutter/lib/src/version.dart, packages/supabase_flutter/pubspec.yaml, packages/yet_another_json_isolate/CHANGELOG.md, packages/yet_another_json_isolate/pubspec.yaml
Also includes a small change to `melos.yaml` to copy the proper version number long with `dev` suffix to each `version.dart` file.
=> chore: publish v2.0.0-dev.0

CHANGELOG.md, packages/gotrue/CHANGELOG.md, packages/gotrue/lib/src/gotrue_client.dart, packages/postgrest/CHANGELOG.md, packages/realtime_client/CHANGELOG.md, packages/realtime_client/lib/src/realtime_channel.dart, packages/realtime_client/lib/src/realtime_client.dart, packages/realtime_client/lib/src/version.dart, packages/realtime_client/pubspec.yaml, packages/storage_client/CHANGELOG.md, packages/supabase/CHANGELOG.md, packages/supabase/lib/src/supabase_client.dart, packages/supabase/lib/src/version.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/CHANGELOG.md, packages/supabase_flutter/lib/src/version.dart, packages/supabase_flutter/pubspec.yaml
- realtime_client@2.0.0-dev.1
- supabase@2.0.0-dev.1
- supabase_flutter@2.0.0-dev.1
=> chore: release dev preview on next branch

CHANGELOG.md, packages/gotrue/CHANGELOG.md, packages/gotrue/lib/src/version.dart, packages/gotrue/pubspec.yaml, packages/supabase/CHANGELOG.md, packages/supabase/lib/src/version.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/CHANGELOG.md, packages/supabase_flutter/lib/src/version.dart, packages/supabase_flutter/pubspec.yaml
- `gotrue` - `v2.0.0-dev.1`
- `supabase_flutter` - `v2.0.0-dev.2`
- `supabase` - `v2.0.0-dev.2`
=> chore: publish developer preview versions

.github/workflows/postgrest_ci.yml, packages/postgrest/lib/src/postgrest_filter_builder.dart, packages/postgrest/test/reset_helper.dart
=> chore: fix failing CI tests

packages/postgrest/lib/src/postgrest_builder.dart, packages/postgrest/test/transforms_test.dart
fixes https://github.com/supabase/supabase-flutter/issues/718
=> fix: issue where `.range()` not respecting the offset given.

packages/functions_client/README.md, packages/gotrue/README.md, packages/postgrest/README.md, packages/realtime_client/README.md, packages/storage_client/README.md, packages/supabase/README.md, packages/supabase_flutter/README.md
Often times the information on the Readme of the sub-libraries are forgotten to be updated. This PR simplifies the Readme files on the sub-libraries to minimal content with links to the official docs, so that the users would not be lost in out dated information.
=> chore: Simplify Readme for sub-libraries to link out to the official docs. 

packages/supabase_flutter/README.md
Just a tiny fix in the Readme file.
=> fix: Update Provider to OAuthProvider in readme

packages/supabase_flutter/README.md, packages/supabase_flutter/pubspec.yaml
- Updates app_link to v3.5.0, which contains linux support.
- Updates the deep link instruction to just link to app_link readme
Fixes https://github.com/supabase/supabase-flutter/issues/278
=> feat(supabase_flutter): Update app_link to v3.5.0, to add Linux support for deep links

packages/functions_client/lib/src/functions_client.dart
I meant to add this comment in https://github.com/supabase/supabase-flutter/pull/905, but I accidentally merged it before pushing it.
=> chore: Add comment about using SSE on the web

CHANGELOG.md, packages/functions_client/CHANGELOG.md, packages/functions_client/lib/src/version.dart, packages/functions_client/pubspec.yaml, packages/gotrue/CHANGELOG.md, packages/gotrue/lib/src/version.dart, packages/gotrue/pubspec.yaml, packages/supabase/CHANGELOG.md, packages/supabase/lib/src/version.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/CHANGELOG.md, packages/supabase_flutter/lib/src/version.dart, packages/supabase_flutter/pubspec.yaml
- functions_client@2.1.0
- gotrue@2.6.1
- supabase_flutter@2.5.2
- supabase@2.1.2
=> chore(release): Publish packages v2.5.2

packages/functions_client/lib/src/functions_client.dart, packages/functions_client/test/custom_http_client.dart, packages/functions_client/test/functions_dart_test.dart
Adding query parameters support for edge functions. 
Closes #924
Largely inspired from https://github.com/supabase/supabase-swift/pull/376.
cc @dshukertjr
=> feat(functions): Invoke function with custom query params

packages/storage_client/lib/src/types.dart
Adding some comments to clarify the usage of some of the storage symbols. 
There were some symbols missing comment docs.
More symbols have comment docs.
=> chore: Add some comments on storage symbols. 

CHANGELOG.md, packages/gotrue/CHANGELOG.md, packages/gotrue/lib/src/version.dart, packages/gotrue/pubspec.yaml, packages/supabase/CHANGELOG.md, packages/supabase/lib/src/version.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/CHANGELOG.md, packages/supabase_flutter/lib/src/version.dart, packages/supabase_flutter/pubspec.yaml
- gotrue@2.8.0
- supabase@2.2.1
- supabase_flutter@2.5.5
=> chore(release): Publish packages supabase_flutter@2.5.5

CHANGELOG.md, packages/gotrue/CHANGELOG.md, packages/gotrue/lib/src/version.dart, packages/gotrue/pubspec.yaml, packages/supabase/CHANGELOG.md, packages/supabase/lib/src/version.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/CHANGELOG.md, packages/supabase_flutter/lib/src/version.dart, packages/supabase_flutter/pubspec.yaml
- gotrue@2.8.1
- supabase@2.2.2
- supabase_flutter@2.5.6
=> chore(release): Publish packages supabase_flutter@2.5.6

CHANGELOG.md, packages/gotrue/CHANGELOG.md, packages/gotrue/lib/src/version.dart, packages/gotrue/pubspec.yaml, packages/supabase/CHANGELOG.md, packages/supabase/lib/src/version.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/CHANGELOG.md, packages/supabase_flutter/lib/src/version.dart, packages/supabase_flutter/pubspec.yaml
- gotrue@2.8.2
- supabase@2.2.3
- supabase_flutter@2.5.7
=> chore(release): Publish packages supabase_flutter@2.5.7

CHANGELOG.md, packages/supabase/CHANGELOG.md, packages/supabase/lib/src/version.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/CHANGELOG.md, packages/supabase_flutter/lib/src/version.dart, packages/supabase_flutter/pubspec.yaml
- supabase@2.2.5
- supabase_flutter@2.5.9
=> chore(release): Publish packages supabase_flutter@2.5.9

CHANGELOG.md, packages/functions_client/CHANGELOG.md, packages/functions_client/lib/src/version.dart, packages/functions_client/pubspec.yaml, packages/postgrest/CHANGELOG.md, packages/postgrest/lib/src/version.dart, packages/postgrest/pubspec.yaml, packages/supabase/CHANGELOG.md, packages/supabase/lib/src/version.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/CHANGELOG.md, packages/supabase_flutter/example/pubspec.yaml, packages/supabase_flutter/lib/src/version.dart, packages/supabase_flutter/pubspec.yaml, packages/yet_another_json_isolate/CHANGELOG.md, packages/yet_another_json_isolate/pubspec.yaml
- yet_another_json_isolate@2.0.1
- postgrest@2.1.3
- functions_client@2.3.1
- supabase@2.2.7
- supabase_flutter@2.5.11
=> chore(release): Publish packages supabase_flutter@2.5.11

CHANGELOG.md, packages/functions_client/CHANGELOG.md, packages/functions_client/lib/src/version.dart, packages/functions_client/pubspec.yaml, packages/gotrue/CHANGELOG.md, packages/gotrue/lib/src/version.dart, packages/gotrue/pubspec.yaml, packages/postgrest/CHANGELOG.md, packages/postgrest/lib/src/version.dart, packages/postgrest/pubspec.yaml, packages/realtime_client/CHANGELOG.md, packages/realtime_client/lib/src/version.dart, packages/realtime_client/pubspec.yaml, packages/storage_client/CHANGELOG.md, packages/storage_client/lib/src/version.dart, packages/storage_client/pubspec.yaml, packages/supabase/CHANGELOG.md, packages/supabase/lib/src/version.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/CHANGELOG.md, packages/supabase_flutter/example/pubspec.yaml, packages/supabase_flutter/lib/src/version.dart, packages/supabase_flutter/pubspec.yaml, packages/yet_another_json_isolate/CHANGELOG.md, packages/yet_another_json_isolate/pubspec.yaml
- functions_client@2.3.2
- gotrue@2.8.4
- postgrest@2.1.4
- realtime_client@2.2.1
- storage_client@2.0.3
- supabase@2.3.0
- supabase_flutter@2.6.0
- yet_another_json_isolate@2.0.2
=> chore(release): Publish packages supabase_flutter@2.6.0

packages/supabase_flutter/example/.metadata, packages/supabase_flutter/example/analysis_options.yaml, packages/supabase_flutter/example/android/.gitignore, packages/supabase_flutter/example/android/app/build.gradle, packages/supabase_flutter/example/android/app/src/debug/AndroidManifest.xml, packages/supabase_flutter/example/android/app/src/main/AndroidManifest.xml, packages/supabase_flutter/example/android/app/src/main/kotlin/com/example/example/MainActivity.kt, packages/supabase_flutter/example/android/app/src/profile/AndroidManifest.xml, packages/supabase_flutter/example/android/build.gradle, packages/supabase_flutter/example/android/gradle.properties, packages/supabase_flutter/example/android/gradle/wrapper/gradle-wrapper.properties, packages/supabase_flutter/example/android/settings.gradle, packages/supabase_flutter/example/ios/RunnerTests/RunnerTests.swift, packages/supabase_flutter/example/macos/RunnerTests/RunnerTests.swift, packages/supabase_flutter/example/web/index.html
Bug fix
The native android and ios files were quite outdated already.
I've removed the native code and reran `flutter create .`.
=> fix: Update example native code

CHANGELOG.md, packages/functions_client/CHANGELOG.md, packages/functions_client/lib/src/version.dart, packages/functions_client/pubspec.yaml, packages/gotrue/CHANGELOG.md, packages/gotrue/lib/src/version.dart, packages/gotrue/pubspec.yaml, packages/postgrest/CHANGELOG.md, packages/postgrest/lib/src/version.dart, packages/postgrest/pubspec.yaml, packages/realtime_client/CHANGELOG.md, packages/realtime_client/lib/src/version.dart, packages/realtime_client/pubspec.yaml, packages/storage_client/CHANGELOG.md, packages/storage_client/lib/src/version.dart, packages/storage_client/pubspec.yaml, packages/supabase/CHANGELOG.md, packages/supabase/lib/src/version.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/CHANGELOG.md, packages/supabase_flutter/example/pubspec.yaml, packages/supabase_flutter/lib/src/version.dart, packages/supabase_flutter/pubspec.yaml, packages/yet_another_json_isolate/CHANGELOG.md, packages/yet_another_json_isolate/pubspec.yaml
- gotrue@2.9.0
- postgrest@2.2.0
- realtime_client@2.3.0
- storage_client@2.1.0
- supabase@2.4.0
- supabase_flutter@2.7.0
- yet_another_json_isolate@2.0.3
- functions_client@2.3.3
=> chore(release): Publish packages v2.7.0

CHANGELOG.md, packages/gotrue/CHANGELOG.md, packages/gotrue/lib/src/version.dart, packages/gotrue/pubspec.yaml, packages/postgrest/CHANGELOG.md, packages/postgrest/lib/src/version.dart, packages/postgrest/pubspec.yaml, packages/supabase/CHANGELOG.md, packages/supabase/lib/src/version.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/CHANGELOG.md, packages/supabase_flutter/example/pubspec.yaml, packages/supabase_flutter/lib/src/version.dart, packages/supabase_flutter/pubspec.yaml
- gotrue@2.11.0
- postgrest@2.4.0
- supabase@2.6.0
- supabase_flutter@2.8.1
=> chore(release): Publish packages supabase_flutter@2.8.1

CHANGELOG.md, packages/gotrue/CHANGELOG.md, packages/gotrue/lib/src/version.dart, packages/gotrue/pubspec.yaml, packages/realtime_client/CHANGELOG.md, packages/realtime_client/lib/src/version.dart, packages/realtime_client/pubspec.yaml, packages/storage_client/CHANGELOG.md, packages/storage_client/lib/src/version.dart, packages/storage_client/pubspec.yaml, packages/supabase/CHANGELOG.md, packages/supabase/lib/src/version.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/CHANGELOG.md, packages/supabase_flutter/example/pubspec.yaml, packages/supabase_flutter/lib/src/version.dart, packages/supabase_flutter/pubspec.yaml
- gotrue@2.11.1
- realtime_client@2.4.1
- supabase@2.6.1
- supabase_flutter@2.8.2
=> chore(release): Publish packages supabase_flutter@2.8.2

CHANGELOG.md, packages/postgrest/CHANGELOG.md, packages/postgrest/lib/src/version.dart, packages/postgrest/pubspec.yaml, packages/supabase/CHANGELOG.md, packages/supabase/lib/src/version.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/CHANGELOG.md, packages/supabase_flutter/example/pubspec.yaml, packages/supabase_flutter/lib/src/version.dart, packages/supabase_flutter/pubspec.yaml
- postgrest@2.4.1
- supabase@2.6.2
- supabase_flutter@2.8.3
=> chore(release): Publish packages supabase_flutter@2.8.3

CHANGELOG.md, packages/functions_client/CHANGELOG.md, packages/functions_client/lib/src/version.dart, packages/functions_client/pubspec.yaml, packages/realtime_client/CHANGELOG.md, packages/realtime_client/lib/src/version.dart, packages/realtime_client/pubspec.yaml, packages/storage_client/CHANGELOG.md, packages/storage_client/lib/src/version.dart, packages/storage_client/pubspec.yaml, packages/supabase/CHANGELOG.md, packages/supabase/lib/src/version.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/CHANGELOG.md, packages/supabase_flutter/example/pubspec.yaml, packages/supabase_flutter/lib/src/version.dart, packages/supabase_flutter/pubspec.yaml
- functions_client@2.4.1
- realtime_client@2.4.2
- storage_client@2.3.1
- supabase@2.6.3
- supabase_flutter@2.8.4
=> chore(release): Publish packages supabase_flutter@2.8.4

.gitignore, packages/gotrue/lib/src/broadcast_stub.dart, packages/gotrue/test/mocks/otp_mock_client.dart, packages/gotrue/test/otp_mock_test.dart, packages/postgrest/lib/src/types.dart, packages/storage_client/lib/src/file_stub.dart, packages/supabase_flutter/lib/src/local_storage_stub.dart, packages/supabase_flutter/test/supabase_flutter_test.dart
Just a PR to increase coverage. More coverage-increase PR to come.
=> chore: Test empty local storage

.github/workflows/supabase_flutter.yml, packages/supabase_flutter/example/android/gradle.properties, packages/supabase_flutter/example/android/gradle/wrapper/gradle-wrapper.properties, packages/supabase_flutter/example/android/settings.gradle, packages/supabase_flutter/example/ios/Flutter/AppFrameworkInfo.plist, packages/supabase_flutter/example/ios/Podfile, packages/supabase_flutter/example/ios/Podfile.lock, packages/supabase_flutter/example/ios/Runner.xcodeproj/project.pbxproj, packages/supabase_flutter/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, packages/supabase_flutter/example/ios/Runner.xcworkspace/contents.xcworkspacedata, packages/supabase_flutter/example/ios/Runner/Info.plist, packages/supabase_flutter/example/macos/Podfile, packages/supabase_flutter/example/macos/Podfile.lock, packages/supabase_flutter/example/macos/Runner.xcodeproj/project.pbxproj, packages/supabase_flutter/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, packages/supabase_flutter/example/macos/Runner.xcworkspace/contents.xcworkspacedata
Run CI on all available platforms, and verify examples builds.
=> ci: Run CI on all platforms

packages/gotrue/test/src/constants_test.dart, packages/gotrue/test/src/helper_test.dart, packages/gotrue/test/src/types/auth_exception_test.dart, packages/gotrue/test/src/types/session_test.dart, packages/gotrue/test/src/types/user_test.dart
No functional changes. Just adding more test cases to improve code coverage of gotrue.
=> chore(gotrue): Improve test coverage

.github/workflows/title-validation.yml
Bug fix, feature, docs update, ...
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
=> chore: update title validation workflow for PRs

.github/workflows/release-prepare.yml
Bug fix, feature, docs update, ...
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
=> chore: remove publish-dry-run check
