README.md, lib/src/supabase.dart, lib/src/supabase_auth_required_state.dart, lib/src/supabase_auth_state.dart, lib/src/supabase_deep_linking_mixin.dart, lib/src/supabase_state.dart, test/supabase_flutter_test.dart
Rework the singleton
To initialize it:
```dart
import 'package:supabase_flutter/supabase_flutter.dart';
void main() {
WidgetsFlutterBinding.ensureInitialized();
Supabase(
url: SUPABASE_URL,
anonKey: SUPABASE_ANNON_KEY,
authCallbackUrlHostname: 'login-callback', // optional
debug: true // optional
);
runApp(MyApp());
}
```
To access the supabase instance:
```dart
import 'package:supabase_flutter/supabase_flutter.dart';
final response = await Supabase().client.auth.signIn(email: _email, password: _password);
```
To initialize it:
```dart
import 'package:supabase_flutter/supabase_flutter.dart';
void main() {
WidgetsFlutterBinding.ensureInitialized();
Supabase.initialize(
url: SUPABASE_URL,
anonKey: SUPABASE_ANNON_KEY,
authCallbackUrlHostname: 'login-callback', // optional
debug: true // …
```
=> Rework the implementation

lib/src/supabase.dart, lib/src/supabase_auth.dart, lib/src/supabase_auth_required_state.dart, lib/src/supabase_auth_state.dart, lib/src/supabase_deep_linking_mixin.dart, lib/supabase_flutter.dart, test/supabase_flutter_test.dart
Feature and bug fix
Currently, the user session is not recovered from storage when the app is initialized.
Fetch the user session from storage when recovered
Fix for #11
This pull request also separates the auth logic into a separate singleton (`SupabaseAuth`), in order to make things easier for future PRs (for #8)
=> Move Auth implementation to a separated class

README.md, lib/src/local_storage.dart, lib/src/supabase.dart, lib/src/supabase_auth.dart, pubspec.lock, pubspec.yaml
`shared_preferences` is currently used to store the user session
`hive` is now used.
Fix for #8
Reworked the LocalStorage implementation. `LocalStorage` is now an abstract class that can be extended by others. Some classes are already built-in: 
- `HiveLocalStorage`, that implements Hive as the storage solution to persist the session on the device.
- `EmptyLocalStorage`, that disabled persistence.
An example of how to extend LocalStorage:
```dart
class EmptyLocalStorage extends LocalStorage {
/// Creates a [LocalStorage] instance that disables persistance
const EmptyLocalStorage()
: super(
initialize: _initialize,
hasAccessToken: _hasAccessToken,
accessToken: _accessToken,
removePersistedSession: _removePersistedSession,
persistSession: _persistSession,
);
static Future<void> …
```
=> Rework the LocalStorage implementation

lib/supabase_flutter.dart
Many projects use the analyzer's option of avoiding 'implementation_imports'.
This rule needs to be explicitly ignored for importing LocalStorage.
Also Flutter in vscode doesn't automatically suggest imports for classes which aren't exported / in the src directory. I first looked at the documentation for the right import, and after not finding it, I had to look into the code.
=> Export the LocalStorage class

lib/src/supabase_auth_required_state.dart, lib/src/supabase_auth_state.dart, test/widget_test.dart, test/widget_test_stubs.dart
Currently, sining out from Supabase does not trigger `onUnauthenticated()`. This causes the user to manually update the navigator stack after a successful sign out. With this PR, users will no longer have to manually update the navigator stack upon a successful sign out. 
Closes https://github.com/supabase/supabase-flutter/issues/35
Calling `signout()` out does not trigger `onUnauthenticated()` on neither `SupabaseAuthState` nor `SupabaseAuthRequiredState`, so the user has to manually navigate out from the current page. 
Upon a successful sign out from Supabase, `onUnauthenticated()` is triggered on both `SupabaseAuthState` and `SupabaseAuthRequiredState`. 
N/A
=> feat: Sining out triggers onUnauthenticated()

CHANGELOG.md, pubspec.yaml
Publishes a new version of `supabase_flutter` which includes
- feat: signing out now triggers `onUnauthenticated()`
- feat: export supabase package so that underlying symbols can be imported
- fix: update code samples to reflect breaking change from v0.0.3
- fix: typos on code samples on readme.md
=> chore: publish version 0.2.9

README.md, lib/src/supabase.dart
Documentation update.
Fixes #9 
Fixes #18
#46 
A lot of stuff is not documentated.
| Platform | Email Auth | Provider Auth | Database | Realtime | Storage |
| -------- | :--------: | :-----------: | :------: | :------: | :-----: |
| Android  |     ✅     |      ✅       |    ✅    |    ✅    |   ✅    |
| iOS      |     ✅     |      ✅       |    ✅    |    ✅    |   ✅    |
| macOS    |     ✅     |               |    ✅    |    ✅    |   ✅    |
| Windows  |     ✅     |               |    ✅    |    ✅    |   ✅    |
| Linux    |     ✅     |               |    ✅    |    ✅    |   ✅    |
=> Documentation updates

CHANGELOG.md, lib/src/supabase_auth.dart, pubspec.yaml
OAuth is now blocked inside embedded browsers by Facebook, Google and others. Authentication page should always be opened in an external browser. This fix addresses that.
=> Bugfix: OAuth should open in an external browser

README.md
This PR brings the example section that [supabase-dart](https://github.com/supabase-community/supabase-dart) has on its readme as most people who use this package will not see the readme of supabase-dart. 
Also, there are a number of people who claim that `stream()` stops emitting realtime changes after setState (issue [here](https://github.com/supabase-community/supabase-flutter/issues/68)). Fixing the bug would be great, but at least adding a workaround in the readme for now would help people out.
=> feat: Add example codes on readme on how to use each feature

CHANGELOG.md, pubspec.yaml
In the previous version, I had made a mistake, and hadn't updated the underlying `supabase-dart` version. This one corrects that mistake.
=> chore: publish v0.3.3

lib/src/supabase_auth.dart
Currently, the initial deep link is handled asynchronously. This means that if the app was launched with a deeplink containing session, the session is still null on app launch. This could be a bit of counter intuitive developer experience. 
This PR awaits the initial deep link handling so that if there were auth links on the initial app launch, the session will be present at the very beginning.
Related https://github.com/supabase/supabase/discussions/9793#discussioncomment-3970711
=> fix: await for the initial deeplink to be handled during auth initialize

lib/src/supabase_auth.dart
With the current setup, Flutter web application will try to parse every URL as a auth call back URL, which results in `No access_token detected` error, causing confusion for developers getting started with Supabase and Flutter web. With this PR, the link will only be parsed, if it contains `access_token` in the query parameter. I remember @DanMossa suggesting implementing something like this, and I should have listened back then 😂
Fixes https://github.com/supabase/supabase-flutter/issues/274
=> fix: only parse deep link if it has access token

lib/src/supabase_auth.dart, pubspec.yaml
Currently [pub.dev](https://pub.dev/packages/supabase_flutter/score) states that this package doesn't support web, because of the `dart:io` import. I've changed it to `universal_io`, which should fix the issue. This doesn't add a new dependency, as the sub libraries are already using it.
=> fix: show web support on pub.dev

README.md, lib/src/supabase_auth.dart, pubspec.yaml
The previous fix didn't work, because universal_io is still listed as not supported. I'm now hard coding the supported platforms as described [here](https://dart.dev/tools/pub/pubspec#platforms). Hopefully it works this time.
I added a section about linux support in the readme, because one might think we don't support linux at all.
=> fix: declare web support

README.md
Doc update
The current doc code for Apple native auth is not correct.
The new behavior changes the provider from Google to Apple, and critically includes the nonce, non-hashed, in the constructor. 
=> Update documentation to reflect correct code for Apple auth login

README.md
Readme update.
The verbage on the readme is a but unclear, and might lead users to assume that native sign in is now supported cross-platform.
Adds text explaining the state of native auth, and links a relevant issue.
=> Make readme clearer around native sign in progress

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/ci.yml
It's helpful to know the version of the sub libraries, so I added this oneliner to get these versions. I outputs the following for this repo:
```bash
supabase_flutter 1.6.0
├── supabase 1.6.1
│   ├── functions_client 1.1.1
│   ├── gotrue 1.5.2
│   ├── postgrest 1.2.2
│   ├── realtime_client 1.0.3
│   ├── storage_client 1.2.3
```
`flutter format` is deprecated, so I'm switching to `dart format`
=> chore: improve version reporting in issue template

lib/src/supabase_auth.dart, test/supabase_flutter_test.dart, test/widget_test_stubs.dart
Coming from supabase/gotrue-dart#126 I'm catching all erros here. You can still use the `initialSession` as before, but if you are not using it, you don't get spammed with the error. Since using the stream in the next release is recomended, right?
=> fix: catch initial session

.github/workflows/ci.yml, README.md, example/analysis_options.yaml, example/macos/Flutter/GeneratedPluginRegistrant.swift, lib/src/supabase_auth.dart, pubspec.yaml
After the very long wait, Supabase is bringing proper native mobile auth! There is a `bundleId` field within the Supabase dashboard that you can add your iOS bundle ID to start using Apple login for both iOS and other platforms. This only allows a single iOS app to be used with a single Supabase instance, but we will take care of that in the later times. 
In the mean while, implementing Apple login could be kind of complicated. We have had the `signInWithIdToken` method thanks to @DanMossa for a while, but the process of signing a user in requires generating nonce and verifying it, and just a whole bunch of stuff that the developers don't really need to worry about. 
I propose to add a `signInWithApple()` method that allows supabase_flutter user to implement Apple login with just one …
=> feat: Add `signInWithApple` method

lib/src/supabase_auth.dart
Currently in order to open in app webivew on iOS to perform OAuth login, the developer has to pass `context, and set the authScreenLaunchMode to `inAppWebView`. This PR also allows the in app webview to open up on iOS for `platformDefault` as the launch mode as well providing a more intuitive developer experience. 
Also fixes an issue where there is an unnecessary `pop` happening after signing in.
Fixes https://github.com/supabase/supabase-flutter/issues/428
=> feat: allow platformDefault to open in app webview for iOS

CHANGELOG.md, lib/src/supabase_auth.dart, lib/src/version.dart, pubspec.yaml
Opening in app browser with Google OAuth login on Android will fail because of [Google's policy](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html). This PR ensures that Google login on Android always opens external browser.
Fixes https://github.com/supabase/supabase-flutter/issues/357
=> fix: google login on android will always open external browser

packages/supabase_flutter/lib/src/supabase_auth.dart
Fixes https://github.com/supabase/supabase-flutter/issues/466
Bug fix
https://github.com/supabase/supabase-flutter/issues/466
It works without throwing.
=> fix(supabase_flutter): prevent Platform.environment use on web

packages/gotrue/lib/src/types/provider.dart
Kakao auth provider sign in method has been added by this PR & doc
[Kakao Auth PR](https://github.com/supabase/gotrue/pull/834)
[Kakao Auth docs PR](https://github.com/supabase/supabase/pull/14287)
To support Kakao provider in the future releases in supabase-flutter, I have come up with this PR.
No kakao provider option for Provider enum type
Please link any relevant issues here.
Kakao provider option for Provider enum type
If there's other changes needed, please let me know.
=> feat: Add kakao provider enum type

packages/gotrue/lib/src/types/provider.dart
A quick reformat Provider type to be ordered alphabetically.
I forgot to order Provider type alphabetically in the previous PR #470 .
=> fix: reformat Provider type to be ordered alphabetically

.github/workflows/supabase_flutter_publish.yml
I pushed the tag for release, but the associated workflow failed. This should hopefully fix that.
https://github.com/supabase/supabase-flutter/actions/runs/5000004116/jobs/8956914310
It's a combination of the following:
https://github.com/leancodepl/patrol/blob/master/.github/workflows/patrol-publish.yaml
https://github.com/leancodepl/mobile-tools/blob/master/.github/actions/pub-release/action.yaml
=> ci: fix publishing supabase_flutter

.github/workflows/functions_client_ci.yml, .github/workflows/gotrue_ci.yml, .github/workflows/postgrest_ci.yml, .github/workflows/realtime_client_ci.yml, .github/workflows/storage_client_ci.yml, .github/workflows/supabase_ci.yml, .github/workflows/supabase_flutter_ci.yml, .github/workflows/yet_another_json_isolate_ci.yml, packages/postgrest/lib/src/postgrest_query_builder.dart, packages/realtime_client/lib/src/transformers.dart, packages/supabase_flutter/test/widget_test_stubs.dart
- Format the files so that `melos run lint:all` passes on the most recent stable version of Flutter, which is v3.10.1.
- Add branch filter on the `push` action for CI actions to not run on pull request pushes. 
@Vinzent03 I apologize. I think I misunderstood something [here](https://github.com/supabase/supabase-flutter/pull/469#issuecomment-1550367300), and yes each test running twice makes it hard to grasp what is going on. Hopefully this PR fixes it.
=> fix: Format the files to adjust to Flutter 3.10.1

.github/workflows/functions_client_ci.yml, .github/workflows/gotrue_ci.yml, .github/workflows/postgrest_ci.yml, .github/workflows/realtime_client_ci.yml, .github/workflows/storage_client_ci.yml, .github/workflows/supabase_ci.yml, .github/workflows/supabase_flutter_ci.yml, .github/workflows/yet_another_json_isolate_ci.yml
There were many duplicates in the test names. Sould look much cleaner now.
Additionally I added that the formatter only runs on stable sdk to prevent failing test just because the formatter changed.
=> ci: cleaner test names

packages/postgrest/lib/src/postgrest_filter_builder.dart
small correction of an error similar to #104, where the character " generated a bug when converted to the url.
the previous bug fix fixed **Order**, **Limit** and **Range**, but had not fixed **Or**.
=> fix(postgrest): Remove qoutations on foreign table transforms on 'or'

CHANGELOG.md, packages/functions_client/CHANGELOG.md, packages/functions_client/lib/src/version.dart, packages/functions_client/pubspec.yaml, packages/gotrue/CHANGELOG.md, packages/gotrue/lib/src/version.dart, packages/gotrue/pubspec.yaml, packages/postgrest/CHANGELOG.md, packages/postgrest/lib/src/version.dart, packages/postgrest/pubspec.yaml, packages/realtime_client/CHANGELOG.md, packages/realtime_client/lib/src/version.dart, packages/realtime_client/pubspec.yaml, packages/storage_client/CHANGELOG.md, packages/storage_client/lib/src/version.dart, packages/storage_client/pubspec.yaml, packages/supabase/CHANGELOG.md, packages/supabase/lib/src/version.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/CHANGELOG.md, packages/supabase_flutter/lib/src/version.dart, packages/supabase_flutter/pubspec.yaml, packages/yet_another_json_isolate/CHANGELOG.md, packages/yet_another_json_isolate/pubspec.yaml
All packages are being updated, because we updated the Dart SDK constraints here https://github.com/supabase/supabase-flutter/pull/474
- functions_client@1.3.0
- gotrue@1.8.0
- postgrest@1.3.0
- realtime_client@1.1.0
- storage_client@1.4.0
- supabase@1.9.0
- supabase_flutter@1.10.0
- yet_another_json_isolate@1.1.0
=> chore(release): publish packages

packages/supabase/lib/src/supabase_query_builder.dart
After seeing [this issue](https://github.com/supabase/supabase/issues/14579), I thought it might make sense to add some more details on the comment docs of `.stream()`.
=> docs(supabase): update comment docs on stream

melos.yaml, packages/supabase_flutter/example/pubspec.yaml
The workflow failes for supabaes_flutter, if the version of supabase changes. https://github.com/supabase/supabase-flutter/actions/runs/5040611117/jobs/9039549791
Instead I'm now using a normal version and include it in melos
=> ci: use melos for example

packages/gotrue/lib/src/gotrue_client.dart, packages/gotrue/test/admin_test.dart, packages/gotrue/test/client_test.dart, packages/gotrue/test/utils.dart
close #500
I'm catching specifc errors on sign out like in [gotrue-js](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L1059) to prevent errors being thrown in `signOut()`.
=> fix(gotrue): catch some errors in signOut

packages/realtime_client/lib/src/realtime_channel.dart, packages/supabase/lib/src/supabase_stream_builder.dart
Currently, the error caught in `.subscribe()` is not passed to the `.stream()` method, and therefore users using the `.stream()` method have no way to catch the errors on the realtime subscription. This PR adds the error on caught on the `.subscribe()` using the callback to pass it to the stream controller so that users can catch it using `.stream().listen().onError()`.
=> fix: Add errors from `.subscribe()` to `.stream()` streamController

packages/realtime_client/lib/src/realtime_channel.dart
- Add some basic docs on `.subscribe()` method
- Give names to the parameters of `callback` on `.subscribe()`
=> refactor(realtime_client): Add docs on `.subscribe()` and give callback parameters names

packages/supabase/lib/src/supabase_stream_builder.dart
There is a handy method called `_addException` that adds the error on the streamController and passes a current stack trace if there are none provided. This PR uses the method instead of directly passing the error to the stream.
=> fix(supabase): add stackTrace on stream exception

.github/workflows/functions_client_ci.yml, .github/workflows/gotrue_ci.yml, .github/workflows/postgrest_ci.yml, .github/workflows/realtime_client_ci.yml, .github/workflows/storage_client_ci.yml, .github/workflows/supabase_ci.yml, .github/workflows/yet_another_json_isolate_ci.yml, packages/functions_client/pubspec.yaml, packages/gotrue/lib/src/constants.dart, packages/gotrue/lib/src/types/mfa.dart, packages/gotrue/pubspec.yaml, packages/postgrest/pubspec.yaml, packages/realtime_client/lib/src/constants.dart, packages/realtime_client/pubspec.yaml, packages/storage_client/pubspec.yaml, packages/supabase/pubspec.yaml, packages/yet_another_json_isolate/pubspec.yaml
- Bumps the minimum Dart SDK version to 2.17.0 across all packages
- Also removed the extension methods on Enums to add `name` getter.
=> refactor: bump minimum Dart SDK version to 2.17.0

packages/gotrue/lib/src/gotrue_client.dart
Adds `accessToken` parameter to `signInWithIdToken` method. 
Related https://github.com/supabase/gotrue-js/pull/690
Related https://github.com/supabase/supabase-flutter/issues/399
=> feat(gotrue): add accessToken to `signInWithIdToken` method

packages/gotrue/lib/src/constants.dart, packages/gotrue/lib/src/gotrue_admin_api.dart, packages/gotrue/lib/src/gotrue_client.dart
feature
Add `scope` parameter to `signOut()`.
https://github.com/supabase/gotrue/pull/1112
https://github.com/supabase/gotrue-js/pull/713
=> feat(gotrue): add scope to signOut

packages/gotrue/lib/src/constants.dart
Add new `OtpType.email` and deprecate `OtpType.signup` and `OtpType.magiclink`.
[gotrue pr](https://github.com/supabase/gotrue/pull/885)
[gotrue-js pr](https://github.com/supabase/gotrue-js/pull/642)
=> refactor(gotrue): add email otptype

packages/supabase_flutter/README.md
When there are underscores used in the application name for an Android app, the redirect URL in the form of `'$applicationId:/google_auth'` becomes invalid. This PR updates the Google login instructions to a one that works even the application name contains underscores.
=> fix: update the google auth setup instruction to use reversed client ID

packages/postgrest/lib/src/postgrest_query_builder.dart
A user reported [on Twitter](https://twitter.com/millergodev/status/1678435300157292545) that our docs does not mention that the postgrest methods can be used on views. This PR adds the missing mention.
=> fix(postgrest): update docs to mention views

packages/realtime_client/lib/src/realtime_client.dart
Use authorization header to set initial access token. That's necessary, when passing custom jwt on Supabase initialization.
close #557
=> fix(realtime): use access token from headers

packages/supabase_flutter/README.md
Should be `AuthChangeEvent.signedIn` instead of `AuthChangeEvent.signIn`
Doc update
`AuthChangeEvent.signIn` stated in the README file
Changed to `AuthChangeEvent.signedIn`
-
=> Update AuthChangeEvent constant in README.md

README.md, infra/postgrest/docker-compose.yml, packages/postgrest/lib/src/postgrest_filter_builder.dart, packages/postgrest/lib/src/postgrest_query_builder.dart, packages/postgrest/test/basic_test.dart, packages/postgrest/test/filter_test.dart
- add `any` and `all` version to `like` and `ilike`
- set columns search parameter in bulk insert/upsert to allow missing column in one row
- add `defaultToNull` to use default value instead of null for missing value in bulk insert/upsert
- [postgREST doc](https://postgrest.org/en/stable/references/api/tables_views.html#bulk-insert)
- [postgrest-js pr](https://github.com/supabase/postgrest-js/pull/417) for postgrest 11 changes
- [postgrest-js pr](https://github.com/supabase/postgrest-js/pull/176)  for columns for bulk insert
=> feat(postgrest): updates for postgREST 11

packages/postgrest/lib/src/postgrest_builder.dart, packages/postgrest/lib/src/postgrest_transform_builder.dart, packages/postgrest/test/transforms_test.dart
Before this update, using `maybeSingle` and getting 0 results threw errors on the server. This PR fixes it by not requesting for a single object, but requesting arrays, and on the client side see if the returned array contains 0 or 1 objects. 
Fixes https://github.com/supabase/supabase-flutter/issues/560
=> fix: `maybeSingle` no longer logs error on Postgrest API

packages/realtime_client/lib/src/realtime_channel.dart, packages/realtime_client/lib/src/realtime_client.dart, packages/realtime_client/test/mock_test.dart
- fixes a small, but significant, typo in the timeout event name
- uses the connection close reason as data/payload for the channel error event
close #527
=> fix(realtime_client): correct channel error data

packages/gotrue/lib/src/constants.dart, packages/gotrue/lib/src/gotrue_client.dart
Some `OtpType` enum values were deprecated in this PR, but it seems like Gotrue server requires the deprecated values in some APIs. 
This PR removes the deprecated flag so that the users can use the resend method without deprecation warnings. 
We can add back the deprecation warnings when the backend properly starts accepting the new `email` type. 
Related https://github.com/supabase/gotrue-js/pull/642
Issue report from user https://github.com/supabase/supabase-flutter/pull/517#issuecomment-1646917472
=> fix(gotrue): remove OtpType deprecation and add assertion to check type for resend method

packages/gotrue/lib/src/gotrue_client.dart, packages/gotrue/lib/src/types/session.dart, packages/supabase/lib/src/auth_http_client.dart, packages/supabase/lib/src/supabase_client.dart, packages/supabase/test/client_test.dart, packages/supabase/test/utils.dart
I'm now getting the latest access token when the actual request is done by wrapping the http client with another client, which gets the newest from `gotrue` and sets the headers correctly.
Additionally I made `expiresAt` a late variable to avoid reparsing the jwt each time. And I added `expired`, because I think its a nice addition to easy check the validity of a session. But I'm not sure if some additional padding could be useful. So that a session is maybe 5 seconds before actual expiration, marked as expired.
That technique is inspired from supabase-js
=> fix(supabase): get jwt on http call

packages/postgrest/lib/src/postgrest.dart, packages/postgrest/test/basic_test.dart, packages/supabase/lib/src/supabase_client.dart
Allows developers to easily query custom schema.
Fixes https://github.com/supabase/supabase-flutter/issues/314
There isn't a way to query other schemas once Supabase client is initialized. Some workarounds that I can think about right now would be
- Don't use custom schemas
- Create postgres views/ functions in the public schema for every custom schema table
- `dispose` and re-initialize the client every time when querying custom schema
All of them are kind of painful to implement.
Developers can query custom schema like this:
```dart
final data = await supabase.useSchema('custom_schema').from('table').select();
```
Since `schema` name is already taken, we couldn't name the method `schema()` like how the js SDK does it.
=> feat(postgrest, supabase): add `useSchema()` method for making rest API calls on custom schema.

README.md, packages/supabase_flutter/README.md
Currently on readme.md of supabase_flutter, it says broadcast does not bypass the database. This is false as it actually bypasses the database. This PR fixes the mistake.
=> fix(supabase_flutter): update readme.md on the notes about broadcast

packages/storage_client/lib/src/storage_file_api.dart, packages/storage_client/test/client_test.dart
On certain versions of Storage-api, the `path` value that was supposed to be returned when calling `createSignedUrls()` was missing. This PR adds a safety guard for when the SDK is used against such versions. 
Related https://github.com/supabase/storage-api/issues/353
=> fix(storage_client): prevent the SDK from throwing when null path was returned from calling `createSignedUrls()`

packages/functions_client/lib/src/types.dart, packages/postgrest/lib/src/postgrest_builder.dart, packages/postgrest/lib/src/postgrest_filter_builder.dart, packages/postgrest/lib/src/postgrest_query_builder.dart, packages/postgrest/lib/src/postgrest_rpc_builder.dart, packages/postgrest/lib/src/types.dart, packages/supabase/lib/src/supabase_stream_builder.dart
There are many arguments of type dynamic that should be of type `Object?` or even `Object` instead. It doesn't allow any property access without previously checking   that the object is of the correct type.
The best of this pr is that you can no longer pass null to e.g. `.eq` filter. Which was a runtime issue here https://github.com/supabase/supabase-flutter/pull/580
If used correctly, this pr shouldn't include any breaking change.
=> feat!: use Object? instead of dynamic

packages/gotrue/lib/gotrue.dart
Currently we use the `show` keyword in exporting symbols from constants.dart file in gotrue. This requires us to add the new symbol to the export every time we create a new one. This PR changes to using `hide` to hide what we don't want to export so that new symbols are exported by default instead.
=> fix(gotrue): export everything in constants.dart and hide what we want to hide instead of using show

packages/functions_client/lib/src/functions_client.dart, packages/functions_client/lib/src/types.dart, packages/functions_client/test/custom_http_client.dart
Switches to depend on the response headers on how to parse the response data
That's the way how it's done in `functions-js`  as well. I'm thinking about switching `FunctionResponse.data` to `Object`. That way the user has to verify the response is of their desired type, but I'm unsure this is appreciated.
Close #614
=> fix(functions_client): use header for response parsing

packages/realtime_client/lib/src/realtime_channel.dart, packages/realtime_client/lib/src/realtime_client.dart, packages/realtime_client/test/mock_test.dart
Currently, the realtime_client will contain an exception if the user has a call back registered within `.subscribe` like this:
```dart
supabase
.channel('channel')
.on(...)
.subscribe((status, [error]) {
// `error` will be non-null when the connection is closed for example when the app goes to background mode etc.
});
```
This PR fixes it. 
Fixes https://github.com/supabase/supabase-flutter/issues/579
=> fix(realtime_client): No exception is thrown when connection is closed. 

infra/postgrest/db/00-schema.sql, packages/postgrest/lib/src/postgrest.dart, packages/postgrest/lib/src/postgrest_builder.dart, packages/postgrest/lib/src/postgrest_filter_builder.dart, packages/postgrest/lib/src/postgrest_query_builder.dart, packages/postgrest/lib/src/postgrest_rpc_builder.dart, packages/postgrest/lib/src/postgrest_transform_builder.dart, packages/postgrest/lib/src/raw_postgrest_builder.dart, packages/postgrest/lib/src/response_postgrest_builder.dart, packages/postgrest/lib/src/types.dart, packages/postgrest/test/basic_test.dart, packages/postgrest/test/filter_test.dart, packages/postgrest/test/reset_helper.dart, packages/postgrest/test/resource_embedding_test.dart, packages/postgrest/test/transforms_test.dart, packages/supabase/lib/src/supabase_client.dart, packages/supabase/test/mock_test.dart
feature
The type system makes everything dynamic, which is not very efficient. Additionally, the way a method argument changes the overall return type is not very darty.
By changing the api and class structure, everything is perfectly typed.
Before
```dart
supabase.from('users').insert().select<PostgrestListResponse>('id, messages', FetchOptions(count: CountOption.exact));
supabase.from('users').select('id, messages', FetchOptions(count: CountOption.exact));
supabase.from('users').select('*', FetchOptions(count: CountOption.exact, head: true));
```
After
```dart
supabase.from('users').insert().select('id, messages').count(CountOption.exact);
supabase.from('users').select('id, messages').count(CountOption.exact);
supabase.from('users').count(CountOption.exact);
```
- `FetchOptions` is …
=> feat(postgrest)!: stronger type system for query building

packages/postgrest/lib/src/postgrest_builder.dart
Bug fix
A `FormatException` is thrown on when trying to parse an empty body
The empty body is caught and no decoding is happening.
#627
=> fix: don't try to decode an empty body

.github/workflows/functions_client_ci.yml, .github/workflows/gotrue_ci.yml, .github/workflows/postgrest_ci.yml, .github/workflows/realtime_client_ci.yml, .github/workflows/storage_client_ci.yml, .github/workflows/supabase_ci.yml, .github/workflows/yet_another_json_isolate_ci.yml, melos.yaml, packages/supabase/test/mock_test.dart
- fix the supabase package tests
- add upgrade and outdated scripts to melos to be able to easily upgrade all packages
- remove unused and outdated node version from matrix
=> ci: make test work again

packages/functions_client/lib/src/functions_client.dart, packages/functions_client/lib/src/types.dart, packages/functions_client/test/custom_http_client.dart, packages/functions_client/test/functions_dart_test.dart
On non 2xx status code a normal response is returned,
An exception is thrown on non 2xx status code. This aligns the behavior to the [js client](https://github.com/supabase/functions-js/blob/main/src/FunctionsClient.ts)
=> fix!: throw exception on non 2xx status

packages/gotrue/lib/src/gotrue_client.dart, packages/gotrue/test/client_test.dart, packages/gotrue/test/custom_http_client.dart, packages/supabase/lib/src/auth_http_client.dart
Bug fix for #630 
When a token refresh failed with a socket exception future token refreshes only happen after the specific timer
It's again possible to refresh the token before the timer executes.
The idea with the refresh token completer was to prevent multiple simultaneous requests. That's still achieved, but once a request is done a new request is possible.
=> fix(gotrue, supabase): allow refreshSession after exception

packages/realtime_client/lib/realtime_client.dart, packages/realtime_client/lib/src/push.dart, packages/realtime_client/lib/src/realtime_channel.dart, packages/realtime_client/lib/src/realtime_client.dart, packages/realtime_client/lib/src/realtime_presence.dart, packages/realtime_client/lib/src/types.dart, packages/realtime_client/test/mock_test.dart
- move types from realtime_channel.dart to types.dart
- make the error parameter for `.subscribe()` non optional
- make the status parameter for `subscribe()` an enum instead of a String
- add some documentation to `ChannelFilter`, because I found no way to use an enum for `ChannelFilter.event`, because for broadcast it can be any string
I think that's it for now that can be type wise improved.
=> refactor!(realtime_client): some realtime refactor

packages/supabase/lib/src/supabase_client.dart, packages/supabase/lib/src/supabase_client_options.dart, packages/supabase/lib/supabase.dart, packages/supabase/test/client_test.dart, packages/supabase_flutter/lib/src/flutter_go_true_client_options.dart, packages/supabase_flutter/lib/src/supabase.dart, packages/supabase_flutter/lib/src/supabase_auth.dart, packages/supabase_flutter/lib/supabase_flutter.dart, packages/supabase_flutter/test/supabase_flutter_test.dart, packages/supabase_flutter/test/widget_test.dart
- create package specific config classes in `supabase` and `supabase_flutter`
- make many fields private
- mark `SupabaseAuth.initialize` as internal as I see no reason to manually initialize. It depends on `Supabase.instance` so it can't be initialized alone either.
This aligns a bit with how supabase-js does this, but I've done the naming a bit different.
Actually, I noticed there is not really a reason for a global `SupabaseAuth.instance`, because it only provides access to the localstorage used. So I would be open to remove it and instead make it a simple object of the `Supabase` class in `supabase_flutter`.
=> refactor!: create package specific configs

packages/postgrest/lib/src/postgrest_filter_builder.dart, packages/postgrest/lib/src/postgrest_query_builder.dart, packages/postgrest/test/basic_test.dart, packages/postgrest/test/filter_test.dart, packages/supabase/lib/src/supabase_stream_builder.dart
- rename `is_` and `in_` to `isFilter` and `inFilter`
This should be the last pr from our v2 changes list. Will merge main into next and udpate the READMEs next
=> refactor!: rename is_ and in_ to isFilter and inFilter

README.md, packages/postgrest/README.md, packages/supabase/README.md, packages/supabase_flutter/README.md
Updates the READMEs to the api changes of v2.
Note that I already pushed a merge of `main` into `next` branch without a pull request, because that was easier with the few merge conflicts. But these were only in tests, so everything should be good.
I think the first dev release should be ready after this pr. :tada:
=> docs: update readme to v2

packages/supabase_flutter/lib/src/supabase_auth.dart, packages/supabase_flutter/pubspec.yaml
This could be another controversial PR. This PR basically removes the webview dependency added in this PR https://github.com/supabase/supabase-flutter/pull/355.
The original reason for adding the webview was to fix issues of browser window not automatically going back tot he app when performing `signInWithOAuth()`, but with Supabase having native OAuth support for Apple and Google login, I think the use cases of using the webview are limited, and I think we are rather safe just dropping it from the dependencies.
=> refactor!(supabase_flutter): Remove webview from dependencies

packages/supabase_flutter/README.md, packages/supabase_flutter/lib/src/supabase_auth.dart, packages/supabase_flutter/pubspec.yaml
I know this PR could be controversial, but I want to hear what you all think. This PR includes the following
- Removes the `signInWithApple()` method
- Make `generateRawNonce method available for developers to easily generate a secure nonce. 
I think it's okay to remove sign_in_with_apple dependencies, as I see a lot of developers implementing Google login despite it being far more complicated than signing in with Apple. I think by looking at this, we learned that developers will be happy as long as there is a way to implement Apple sign in, so I personally think we should remove sign_in_with_apple dependencies, but am open to comments. 
Related: https://github.com/supabase/supabase-flutter/issues/399#issuecomment-1610598390
=> refactor!:  remove `signInWithApple` method and make `generateRawNonce` public

packages/realtime_client/lib/src/realtime_channel.dart, packages/realtime_client/lib/src/realtime_client.dart, packages/realtime_client/pubspec.yaml, packages/realtime_client/test/channel_test.dart
feature
Enables sending messages to server via a broadcast HTTP endpoint request instead of waiting for a WebSocket connection, subscribing to a channel, and then sending messages.
js pr: https://github.com/supabase/realtime-js/pull/251
close #652
=> feat: send messages via broadcast endpoint

packages/gotrue/lib/src/gotrue_client.dart, packages/gotrue/pubspec.yaml, packages/gotrue/test/custom_http_client.dart, packages/storage_client/lib/src/fetch.dart, packages/storage_client/lib/src/file_io.dart, packages/storage_client/lib/src/file_stub.dart, packages/storage_client/lib/src/storage_file_api.dart, packages/storage_client/pubspec.yaml, packages/storage_client/test/custom_http_client.dart
Bug fix
- We only catch `SocketException`, which in only thrown in native Dart, but not for example in dart2js
- We use `File` from `dart:io`
- We instead use `ClientException`, which is also thrown in js runtime as documented [here](https://pub.dev/documentation/http/latest/http/Client-class.html)
- Created a stub for `File` to be able to compile the package with `webdev`
~~This was meant to fix #641, but this would require the removal of `File`, which im very unsure about. I think it makes things MUCH easier to be able to work with `File` on native platform, but somehow not being able to compile this to dart web is a bummer. I'm wondering why this package compiles for Flutter web though.~~
close #641
=> fix: compile with webdev

packages/gotrue/lib/src/gotrue_client.dart
Fixes #658
Bug fix
- #658
- Removed the import dart:io from gotrue_client.dart to enable Dart web apps to be built successfully.
dart:io was only used to refer to `SocketException` in the document of the `_callRefreshToken()` method. `SocketException` was replaced with `ClientException` in 6b5966f3b9fafc796b0a0f7e4c716616826468dd.
=> fix(gotrue): remove import of dart:io from gotrue_client.dart

packages/gotrue/lib/src/gotrue_client.dart, packages/gotrue/test/client_test.dart
Bug fix
When the device is offline the `refreshSession` takes **very** long until all retry attempts are done. This may be unexpected and blocks everything when awaited, as seen when using `Supabase.initialize()`. Additionally, postgrest requests now properly fail with a `ClientException` when being offline and not waiting endless when access token is expired.
`refreshSession` finishes after the first requests and throws when request fails. The refresh token timer is started in the background and emits a valid session to the `onAuthStateChange` stream when available.
This is hopefully the last pr to that refresh token offline issue...
close #630
=> fix: token refresh doesn't block on ClientException

packages/supabase/lib/src/counter.dart, packages/supabase/lib/src/supabase_client.dart, packages/supabase/lib/src/supabase_query_schema.dart, packages/supabase/lib/src/supabase_wrapper.dart, packages/supabase/lib/supabase.dart
Bug fix
When using `client.useSchema("mySchema").from("myTabel")` you can't append `.stream()`
You can now stream from a different schema.
close #610
=> fix: stream with a different schema

packages/gotrue/lib/src/gotrue_client.dart
Calling `auth.verifyOtp()` method with the 6-digit OTP returns an `AuthResponse` with `null` session. The supabase_flutter SDK currently however does not allow `null` session returned from the `verifyOtp()` method, but this PR enables empty session to be returned.
=> fix(gotrue): allow empty session response for verifyOtp method

packages/postgrest/lib/src/postgrest_filter_builder.dart, packages/postgrest/lib/src/postgrest_transform_builder.dart, packages/postgrest/test/resource_embedding_test.dart, packages/postgrest/test/transforms_test.dart
There has been a bit of confusion around using the term `foreign table` in context of a table referenced with foreign key constraint after Supabase adding [Supabase wrappers](https://supabase.com/docs/guides/database/extensions/wrappers/overview). An experienced Postgres developer will more likely to think about table connected using foreign data wrappers as foreign tables, and not a table that is referenced by a foreign key constraint when they hear the term `foreign table`. 
JS PR here: https://github.com/supabase/postgrest-js/pull/493
=> refactor!(postgrest): rename `foreignTable` parameter to `referencedTable`

packages/supabase_flutter/README.md
Supabase auth recently added an option to skip the nonce check when performing Google sign in. This would allow developers to finally perform Google sign-in using the official Google sign-in package for both iOS and Android. This PR updates the instruction on Readme to reflect this change.
=> chore(supabase_flutter): Update the instructions to perform Google sign in

infra/postgrest/docker-compose.yml, packages/postgrest/lib/src/postgrest_builder.dart, packages/postgrest/lib/src/postgrest_transform_builder.dart, packages/postgrest/test/transforms_test.dart
Adds a new `.explain()` transformer that will return 
```dart
final String plan = await supabase.from('table').select().explain(); 
// `plan` will be something like this as plain String:
// Aggregate  (cost=8.18..8.20 rows=1 width=112)
//  ->  Index Scan using projects_pkey on projects  (cost=0.15..8.17 rows=1 width=40)
//        Index Cond: (id = 1)
```
The JS SDK has a `json` and `text` response types, but [`text` is preferred](https://github.com/supabase/postgrest-js/pull/302), so I think it's okay to only have `text` for Dart SDK. 
JS implementation here https://github.com/supabase/postgrest-js/blob/master/src/PostgrestTransformBuilder.ts#L245
Closes https://github.com/supabase/supabase-flutter/issues/717
=> feat: adds `.explain()` for debugging performance issues on Supabase client generated queries. 

packages/realtime_client/lib/src/realtime_channel.dart
No functional changes and just hiding what should be hidden. 
Technically it might be a breaking change because it includes making public members private, but users shouldn't really be using them, so the affect should be minimal.
=> refactor!(realtime_client): make channel methods private and add `@internal` label

.github/workflows/gotrue_ci.yml, packages/gotrue/lib/src/constants.dart, packages/gotrue/lib/src/gotrue_client.dart
Currently when the developer calls `auth.signOut()`, it signs out the user from every device. This PR changes the default value to `local`, which is probably more aligned with what a developer would expect to happen when calling `auth.signOut()`.
=> fix!(gotrue): change the default signOut scope to local from global

packages/supabase_flutter/lib/src/local_storage.dart, packages/supabase_flutter/test/widget_test.dart
We have a `MigrationLocalStorage` class for anyone migrating from supabase_flutter v1 to v2 so that the auth session would keep working while we have switched from using hive to using sharedPreferences for storing session data. 
There  is currently a bug where the migration fails. This PR fixes the failing migration.
=> fix(supabase_flutter): session migration from hive to sharedPreferences now works properly

packages/gotrue/lib/src/gotrue_client.dart
Currently when a user signs in with the pkce flow, two `signedIn` events are fired. This PR makes it one.
=> fix(gotrue): signing in with pkce flow fires two `signedIn` auth event

packages/supabase_flutter/lib/src/local_storage.dart
Bug fix
Due to a missing else/return statement, SharedPreferences is used.
Skip the SharedPreferences access.
close #703
=> fix: use SharedPreferences on web

packages/postgrest/lib/src/postgrest.dart, packages/postgrest/test/basic_test.dart, packages/supabase/lib/src/supabase_client.dart, packages/supabase/lib/src/supabase_query_schema.dart
Currently the JS library uses `.schema()` to change the schema for calling APIs to non-public schema. However, the Dart library uses `useSchema()`, because `schema` symbol was already taken by the [`schema`](https://github.com/supabase/supabase-flutter/blob/main/packages/postgrest/lib/src/postgrest.dart#L10) variable in postgrest.dart. 
This PR renames the `schema` variable to `_schema` and `.useSchema()` to `.schema()` to align the public API with the JS library.
```dart
await supabase.useSchema('custom_schema').from('table').select();
```
```dart
await supabase.schema('custom_schema').from('table').select();
```
=> refactor!(postgrest, supabase): make `schema` variable private and rename `useSchema()` to `schema()`

packages/gotrue/lib/src/gotrue_client.dart
Bug fix
When a token refresh fails with the error that it's already used, just an error is thrown.
Every Token refresh failure issues a sign out.
close #710
=> fix: sign out on already used refresh token

packages/supabase/lib/src/supabase_stream_builder.dart
Bug fix
Ordering double values is not supported for realtime events in streams.
All nums are supported.
close #691
=> fix: realtime ordering on double

packages/gotrue/lib/src/types/o_auth_provider.dart
Bug fix
Figma is not listed as a provider even though supabase supports it
Figma is now listed as a provider
I tested getOAuthSignInUrl with Provider.figma and it worked as expected. (admittably it was on v1)
=> feat(gotrue): add Figma to  OAuth provider.

packages/supabase_flutter/README.md
Updates the instructions on how to perform Apple login on readme.md file of supabase_flutter.
=> fix: update sign in with Apple instruction on readme

packages/gotrue/lib/gotrue.dart, packages/gotrue/lib/src/constants.dart, packages/gotrue/lib/src/gotrue_client.dart, packages/supabase_flutter/test/supabase_flutter_test.dart
Currently with PKCE flow, `passwordRecovery` auth event is not emitted for email password reset flow. This PR fixes it.
`signIn` event is emitted after clicking on the link sent to the email.
`passwordRecovery` event is emitted after opening the link sent to the email.
Fixes https://github.com/supabase/supabase-flutter/issues/664
=> fix: PKCE flow not emitting password recovery event

packages/realtime_client/lib/src/realtime_channel.dart, packages/realtime_client/lib/src/realtime_presence.dart, packages/realtime_client/lib/src/types.dart, packages/realtime_client/test/channel_test.dart
Currently, a lot of data passed around the realtime presence feature relies on `Map`. Some of them have very weird typing using Map such as the return type of `channel.presenceState()` being `Map<String, List<Presence>>`. This PR aims to add better typing for better developer experiences. 
`payload` in callback is `Map<String, dynamic>` when the SDK knows a bit more about what data could come in.
Also `channel.presenceState()` has `Map<String, List<Presence>>` as its return type;
```dart
channel = supabase
.channel('name')
.onPresence(
event: PresenceEvent.sync,
callback: (payload) {
print(payload); // `payload` is type `Map<String, dynamic>`
print(channel.presenceState()); // prints `{'UUID': [Presence(key: 'presenceKey', payload: {'my': 'payload'})]}
},
).subscribe();
````
Now …
=> feat!(realtime_client): Provide better typing for realtime presence.

packages/storage_client/lib/src/file_stub.dart
Bug fix
```dart
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:universal_io/io.dart';
final String path = '$userId/${i.toString()}';
final String res;
if (!kIsWeb) {
final File file = File("myPath");
res = await _supabase.storage
.from('profile')
.upload(path, file));
}
```
Even though the if body will never be called on web, the compiler still throws an error that two different `File` implementations are used, because we stub `File` on web in `storage_client`.
```
Error: The argument type 'File/*1*/' can't be assigned to the parameter type 'File/*2*/'.
- 'File/*1*/' is from 'dart:io'.
- 'File/*2*/' is from 'package:storage_client/src/file_stub.dart' ('../../../.pub-cache/hosted/pub.dev/storage_client-1.5.4/lib/src/file_stub.dart').
.upload(path, file);
```
On …
=> fix: web compilation

packages/gotrue/lib/src/gotrue_client.dart
feature
There's no `getUser` method to get a user object from a jwt.
Add `getUser`
close #752
=> feat: add getUser() method

packages/supabase_flutter/example/lib/main.dart, packages/supabase_flutter/example/macos/Flutter/GeneratedPluginRegistrant.swift, packages/supabase_flutter/example/pubspec.yaml, packages/supabase_flutter/lib/src/supabase_auth.dart, packages/supabase_flutter/lib/supabase_flutter.dart
Currently `signInWithOAuth()` and `generateRawNonce()` are not exported in `supabase_auth.dart` file. This PR updates the export to make those methods available.
Fixes https://github.com/supabase/supabase-flutter/issues/762
=> fix(supabase_flutter): export `signInWithOAuth()` and `generateRawNonce()`

packages/postgrest/lib/src/postgrest_query_builder.dart, packages/postgrest/test/basic_test.dart
Currently when performing count with head: true, we cannot chain filters (eq, match, etc.). 
This PR will allow filters to be chained on `.count()` like this:
```dart
final int count = await supabase.from('table')
.count() // count with head: true
.eq('name', 'Supabase');
```
Might not be anything to be too concerned about, but wanted to leave a note here. The change in this PR will actually allow a whole bunch of other things to be chained to `.count()` that doesn't make a whole lot of sense. 
```dart
final res = await supabase.from('table')
.count()
.eq('name', 'Supabase')
.limit(1) // It's a head request, and limits and ranges are ignored for count request, so this is not doing anything
.withConverter<List<int>>((data) => [data]); // `data` here is the count value of type int. Again, …
```
=> fix: enable filtering and tranformation on count with head

packages/postgrest/lib/src/postgrest_filter_builder.dart, packages/postgrest/test/filter_test.dart
Currently passing `null` to `not()` filter is not allowed. This PR makes it possible. 
Fixes https://github.com/supabase/supabase-flutter/issues/772
=> fix: Passing `null` to `not()` filter is now allowed

packages/gotrue/lib/src/gotrue_client.dart
This fixes issue #773
`verifyOTP` emits `AuthChangeEvent.signedIn` when `OtpType.recovery` is passed
`verifyOTP` emits `AuthChangeEvent.passwordRecovery` when `OtpType.recovery` is passed
This allows listeners to properly navigate the user to the password reset screen rather than the default home screen after verification.
=> fix(gotrue): Fix the issue where `verfiyOTP` emits `signIn` instead of `passwordRecovery` auth event.

infra/gotrue/db/00-schema.sql, infra/gotrue/docker-compose.yml, packages/gotrue/lib/src/fetch.dart, packages/gotrue/lib/src/gotrue_client.dart, packages/gotrue/lib/src/types/auth_response.dart, packages/gotrue/lib/src/types/user.dart, packages/gotrue/test/client_test.dart, packages/supabase_flutter/lib/src/supabase_auth.dart
This PR brings one of the core auth launch announced at LWX.
Add a method to retrieve URL for manual linking OAuth providers, and adds a method to launch the URL obtained from Gotrue to supabase_flutter.
Manual identity linking is not possible using supabase_flutter.
Manual identity linking is now poissible.
=> feat(gotrue, supabase_flutter): Add identity linking and unlinking methods.

packages/postgrest/lib/src/types.dart
Make PostgrestException serialisable by implementing the toJson method.
I was having some issues due to PostgrestException, since I keep track of errors in the Redux store, and persist it.  TBH, I was thinking I do not really want to store an exception as is or display it to the user directly, but I would like not to lose the information, maybe embed it in a user-friendly error, but keep the option to send it to the backend (e.g. via Sentry). So serialisation would be nice to have!
```
Converting object to an encodable object failed: Instance of 'PostgrestException'
```
It just implements the toJson. I feel this didn't really need a test, but I can add serialisation/deserialisation roundtrip if you like ✌️ 
Thanks!
=> feat(postgrest): Add `toJson()` method to `PostgrestException` to allow serialization

packages/gotrue/lib/src/gotrue_client.dart, packages/gotrue/lib/src/types/o_auth_provider.dart
feature
Adds the `linkedin_oidc` OAuthProvider.
- [js pr](https://github.com/supabase/gotrue-js/pull/796)
- close #779
=> feat: Add linkedin_oidc OAuthProvider

packages/supabase_flutter/lib/src/local_storage.dart
Currently when initializing Supabase within Safari while dev tool is opened, `Supabase.initialize()` hangs leaving the user with just a white screen.
This is caused by `await Hive.openBox(_hiveBoxName, encryptionCipher: encryptionCipher);` hanging. Although the reason for why the function does not complete is unknown, we could at least add a timeout so that when it does hang, we can at least catch the `TimeoutException` and proceed. 
Fixes https://github.com/supabase/supabase-flutter/issues/794
=> fix(supabase_flutter): Add timeout to Hive.openBox to fix hanging issue

packages/gotrue/lib/src/gotrue_client.dart, packages/supabase_flutter/lib/src/supabase_auth.dart
Add `signInWithSSO()` method that can be called like the following:
```dart
await supabase.auth.signInWithSSO(
domain: `company.com`
);
```
`signInWithSSO()` works in a similar way as `signInWithOAuth()` where `gotrue-dart` has a `getSSOSignInUrl()` that provides the sign in URL, and supabase_flutter handles the user redirect.
supabase-js implementation here: https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L758
Closes https://github.com/supabase/supabase-flutter/issues/759
=> feat(gotrue, supabase_flutter): Add `signInWithSSO` method

packages/gotrue/lib/src/gotrue_client.dart
Currently when the supabase_flutter SDK obtains the initial session from local storage and calls `setInitialSession()` method of gotrue, the `_currentUser` is not set causing a state where `auth.currentSession` is not null, but `auth.currentUser` being null. This PR fixes it. 
Related https://github.com/supabase/supabase-flutter/issues/805
=> fix(gotrue): Set _currentUser when setting initial session

packages/supabase_flutter/README.md, packages/supabase_flutter/example/linux/flutter/generated_plugin_registrant.cc, packages/supabase_flutter/example/linux/flutter/generated_plugins.cmake, packages/supabase_flutter/lib/src/supabase_auth.dart
- Support deeplink on Linux platform
The app_link package has supported the deep link feature since version 3.5.0.
https://github.com/llfbandit/app_links/pull/76
=> fix: Remove platform check to start deep link observer on every platform including Linux

packages/gotrue/lib/src/gotrue_client.dart
feature
You can't verify a token hash
close #803
=> feat: Add token hash to verifyOtp

packages/storage_client/lib/src/fetch.dart, packages/storage_client/lib/src/storage_bucket_api.dart, packages/storage_client/lib/src/storage_client.dart, packages/storage_client/lib/src/storage_file_api.dart, packages/storage_client/pubspec.yaml, packages/storage_client/test/basic_test.dart, packages/storage_client/test/client_test.dart, packages/storage_client/test/custom_http_client.dart
Bug fix
One global fetch instance is used for all storage clients.
The fetch instance containing the custom http client is now per storage client.
close #771
=> fix: Use per client fetch instance

packages/supabase_flutter/CHANGELOG.md, packages/supabase_flutter/README.md, packages/supabase_flutter/lib/src/local_storage.dart, packages/supabase_flutter/lib/src/supabase.dart, packages/supabase_flutter/pubspec.yaml, packages/supabase_flutter/test/widget_test.dart, packages/supabase_flutter/test/widget_test_stubs.dart
This PR removes the Hive dependency. We said we eventually remove the Hive dependency when we first implemented the automatic migration code. I personally was thinking of keeping the migration code around longer something like 5 or 6 months, and it has only been a month and a half since v2 of supabase_fluter has been published. However, Hive is currently [working on a complete rewrite](https://pub.dev/packages/hive/versions/4.0.0-dev.2/changelog), and it might be good to remove its dependency before they release a stable version of it. I'm open to comments about this PR though. 
If this PR gets merged, I will add a similar section about migrating auth from v1 to v2 in the [upgrade guide](https://supabase.com/docs/reference/dart/upgrade-guide) as well.
Closes …
=> refactor: Remove hive dependency and add instructinos to migration from v1 while persisting the auth state

packages/gotrue/lib/src/gotrue_client.dart, packages/gotrue/test/client_test.dart, packages/supabase_flutter/lib/src/supabase_auth.dart
The SDK should throw an AuthException when parsing an auth URL that contains an error description.
This PR updates the `_isAuthCallbackDeeplink` in supabase_flutter to return `true` if the URL contains `error_description`, and also makes sure proper exception is thrown when parsing auth URL containing an error description.
Related https://github.com/supabase/supabase-flutter/issues/819#issuecomment-1944364896
=> fix(gotrue, supabase_flutter): Throw error when parsing auth URL that contains an error description.

packages/gotrue/lib/src/gotrue_client.dart
Just implemented manual linking, and found that the unlink method just doesnt work cause the wrong id is used.
```
AuthException(message: identity_id must be an UUID, statusCode: 400)
```
Here's the fix :)
=> fix: Correct the id value passed to `.unlinkIdentity()` method

packages/postgrest/lib/src/postgrest_filter_builder.dart
Previous documentation provides code examples that are syntactically incorrect and do not explain how to provide inclusive and exclusive ranges as a value.
This PR does not introduce any code changes, only code documentation changes.
Documentation in VS Code for `contains` and `containedBy` methods was confusing, and looked like an obvious typo. While performing a deeper dive into the methods themselves I discovered I could pass a string with parenthesis or brackets, or an array object as a value. This was not exposed in the code comments for the documentation. I felt compelled to update it.
=> docs(postgrest): Expand documentation for `contains` and `containedBy` methods

packages/realtime_client/lib/src/push.dart, packages/realtime_client/lib/src/realtime_channel.dart, packages/realtime_client/lib/src/realtime_client.dart, packages/realtime_client/lib/src/types.dart, packages/supabase/lib/src/realtime_client_options.dart, packages/supabase/lib/src/supabase_client.dart
Client-side Realtime rate-limiting was causing confusion among developers when they saw that some of their Realtime events were not being reflected. After some discussions by the Realtime team, they concluded that the client side rate limiting behavior is not ideal, and decided to drop it. There is a server side rate limiting feature in place.
This PR deprecates the `eventsPerSecond` and removes client-side rate limiting.
JS implementation: https://github.com/supabase/realtime-js/pull/260
Closes https://github.com/supabase/supabase-flutter/issues/837
=> refactor: Deprecate `eventsPerSecond` on Realtime

packages/supabase_flutter/lib/src/flutter_go_true_client_options.dart, packages/supabase_flutter/lib/src/supabase_auth.dart
js client has [detectSessionInUrl](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L100) option to optionally disable obtaining sessions from URL. This PR adds the same parameter, but renames the end to `uri` from `url`.
Closes https://github.com/supabase/supabase-flutter/issues/847
We've had the following two PRs related to this, but we can finally close these too.
https://github.com/supabase/supabase-flutter/pull/669
https://github.com/supabase/supabase-flutter/pull/605
=> feat: Add `detectSessionInUri` option to optionally disable deep link observer. 

packages/supabase_flutter/README.md
The README.md is not completely precise when providing an example of a Custom Local Storage. 
To check if it hasAccessToken it should return a bool (and so should return storage.containsKey(key: supabasePersistSessionKey) ).
And when retrieving the accessToken it should return a string (so the correct code would be: storage.read(key: supabasePersistSessionKey) )
Docs update
The two functions accessToken() and hasAccessToken() return the wrong type. It's probably simply an oversight when copy-pasting this code.
I swapped the two return lines so that it behaves correctly.
When trying to understand how to create a custom local storage I spent some time figuring out why my code was not behaving correctly, but then saw the wrong return type.
Im new to the open source community so I don't know …
=> docs: Fixed imprecision in Custom Local Storage README.md

packages/realtime_client/lib/src/transformers.dart
- Fix issue where `null` timestamp column value becomes `"null"` string on realtime
Fixes https://github.com/supabase/supabase-flutter/issues/854
=> fix(realtime_client): Fix issue where `null` `timestamp` type column becomes `"null"` string on realtime

packages/supabase_flutter/pubspec.yaml
dependency version bump
Allow app_links version ^3.5.0
Allow app_links version ^4.0.0 as well as ^3.5.0, because no breaking change was made in the api itself. https://pub.dev/packages/app_links/changelog#400
close #863
=> chore: Allow app_links version ^3.5.0 and ^4.0.0

packages/realtime_client/lib/src/realtime_channel.dart, packages/realtime_client/test/channel_test.dart, packages/supabase/lib/src/supabase_client.dart
Bug fix
The access token is sent as `apikey`, but from what I see it doesn't need/take authorization at all.
The `apikey` passed in the default header in realtime client initialization in the supabase package is used. That's the anon apikey and not the user's one. 
I noticed that it was enough to remove the apikey field in the send method, because the `apikey` field gets also set in the `AuthHttpClient` if it's not already set, but I thought it's either way good to add it to the headers directly as well. realtime-js does this as well.
close #867
=> fix: Don't send access token  in rest broadcast

packages/gotrue/lib/src/gotrue_client.dart
Just a small typo I found while reading the docs.
signOut says `dtermines`
signOut says `determines`
💙
=> fix: Typos in gotrue_client.dart

packages/realtime_client/lib/src/realtime_channel.dart
Currently, there is a bug where the `channel.track()` method hangs indefinitely when the server returns an error. This PR fixes the issue. 
JS update here: https://github.com/supabase/realtime-js/pull/290/files
=> fix(realtime_client): Accept an error on track when the server returns an error

packages/gotrue/lib/src/fetch.dart, packages/gotrue/test/client_test.dart
Fixes a bug. 
Currently a format exception with message `type 'List<dynamic>' is not a subtype of type 'List<String>'` is thrown when performing signUp, password update with a week password. 
`AuthWeakPasswordException` is properly thrown when performing signUp/ password update with a week password. 
fixes https://github.com/supabase/supabase-flutter/issues/891
=> fix: Weak password throws `AuthWeakPasswordException`.

packages/gotrue/lib/src/gotrue_admin_api.dart
Bug fix
`newEmail` is missing in the admin `generateLink` method
Added `newEmail` parameter and improved documentation.
close #893
=> fix: Add newEmail to admin generateLink method

packages/functions_client/lib/functions_client.dart, packages/functions_client/lib/src/functions_client.dart, packages/functions_client/lib/src/types.dart, packages/functions_client/test/custom_http_client.dart, packages/functions_client/test/functions_dart_test.dart, packages/supabase/lib/src/auth_http_client.dart
Adds support for streaming response of an edge function that returns Server Sent Events. 
Fixes https://github.com/supabase/supabase-flutter/issues/894
There is no support for SSE, and developers have to use other libraries to listen to SSE. 
Users can listen to SSE like the following:
```dart
final response = await supabase.functions.invoke('sse-function');
response.data
.transform(const Utf8Decoder())
.listen((val) {
print(val);
});
```
On the web, you would need to pass a custom HTTP client like this:
```dart
final client = FetchClient(mode: RequestMode.cors);
await Supabase.initialize(
url: supabaseUrl,
anonKey: supabaseKey,
debug: false,
httpClient: kIsWeb ? client : null,
);
```
=> feat(functions_client): Add SSE support to invoke method

packages/supabase_flutter/pubspec.yaml
Update the dependencies of app_links so that it can use the latest version.
app_links v5.0.0 contains the following update, which shouldn't collide with any of its feature that are being used in supabase_flutter. 
>Breaking iOs: Application Delegate now returns true for both Universal Links and Custom URL schemes. If you have other packages which could conflict with it, report to the README.md for custom handling. This change is motived by the basic deep linking provided by Flutter and the fact that there is now a workaround for such cases.
app_links v5.0.0 cannot be used with supabase_flutter
app_links v5.0.0 can be used with supabase_flutter
=> fix: Update app_links dependency to accept v5.0.0

.github/workflows/supabase_flutter.yml, packages/supabase_flutter/lib/src/supabase_auth.dart, packages/supabase_flutter/pubspec.yaml
Bug fix, dependency version bump
app_links 6.0.0 is not supported
5.0.0 is still supported and 6.0.0 now as well, despite the breaking change, by trying both methods with error catching.
Additionally, the supabase_flutter packages is now tested with downgraded packages versions as well.
#915 wanted to drop support for 5.0.0
=> fix: Keep compatible with app_links 6.0.0 and 5.0.0

packages/gotrue/lib/src/gotrue_client.dart
Allow OAuthProvider.kakao for signInWithIdToken in gotrue_client
Only google and apple are allowed.
https://github.com/supabase/auth/pull/1381
Since supabase.auth already allows an OIDC with kakao, the client should accept the OAuthProvider.kakao with signInWithIdToken
=> feat(goture): Allow OAuthProvider.kakao for signInWithIdToken

packages/postgrest/lib/src/postgrest_filter_builder.dart
Fixes https://github.com/supabase/supabase-flutter/issues/917
Currently, users can pass `null` to `match()` filter. 
Users will not be able to pass `null` to `match()`.
=> fix(postgrest): Update parameter type of `match()` filter so that null values cannot be passed. 

packages/postgrest/lib/src/postgrest_filter_builder.dart
Fixes https://github.com/supabase/supabase-flutter/issues/917
Currently any object can be passed as the value parameter of `isFilter()`
Only null and boolean values can be passed to `isFilter()`
=> fix(postgrest): Update parameter type of `isFilter()` to only allow boolean or null

packages/realtime_client/lib/realtime_client.dart, packages/realtime_client/lib/src/constants.dart, packages/supabase/lib/src/realtime_client_options.dart, packages/supabase/lib/src/supabase_client.dart
Allow the ctor `SupabaseClient` to set `timeout` to a `RealtimeClient`.
Due to the fact the `timeout` is a final field in `RealtimeClient`, we cannot change its value after the `RealtimeClient` is created, and because the `RealtimeClient` is created in the ctor of `SupabaseClient`, there is no way for users to set the timeout.
The new behavior allow us to set the timeout of the `RealtimeClient` like this:
``` dart
final SupabaseClient supabase = SupabaseClient(
'https://your.supabase.address/',
'your_anon_key',
realtimeClientOptions: RealtimeClientOptions(timeout: Duration(minutes: 1)),
);
```
My app is connecting Supabase through Tor proxy. It's normal to cost 10 or more seconds to build a WebSocket connection. However, the current default timeout of `RealtimeClient` is 10 seconds, which …
=> feat: Allow setting `timeout` of `RealtimeClient`.

packages/functions_client/pubspec.yaml, packages/postgrest/pubspec.yaml, packages/supabase/pubspec.yaml, packages/supabase_flutter/pubspec.yaml
Instead of specifying the version range like `"^2.0.0"`, the internal packages are pinned to specific versions. 
supabase-js started doing this recently as well. With this, we can now the versions of the sub-libraries just by obtaining the supabase-flutter version, and it also helps with preventing accidental breaking change affecting a wider range if there were to be one.
=> chore: Internal packages are now imported with version specified

packages/gotrue/lib/src/gotrue_client.dart
Bug fix
Currently, the SDK removes the session whenever a user tries to sign-in / sign-up. If the operation fails, the user is signed out from the original session they had. This PR fixes the behavior so that the session is not removed.
The user's session is not removed at the beginning of calling sign-in / sign-up methods, and they will keep the existing session if the sign-in / sign-up operation fails. 
JS PR: https://github.com/supabase/auth-js/pull/915
=> fix(gotrue): Signing in does not remove the session unless the operation succeeds.

packages/gotrue/lib/src/gotrue_client.dart
Bug fix
The `token` parameter is required.
The `token` parameter is nullable, allow passing only `tokenHash`
close #942
=> fix: Make token in verifyOtp nullable

packages/gotrue/lib/src/fetch.dart, packages/gotrue/lib/src/types/auth_exception.dart
Bug fix.
`
When e.g. an http response with status code 500 is received, an `AuthRetryableFetchException` is thrown without contaning the actual error.
I've added the `message` and `statusCode` to the constructor.
#902
=> fix: Store actual error in AuthException

packages/gotrue/lib/src/types/mfa.dart
Bug fix
The `magiclink` mfa type is not recognized. 
The `magiclink` type is properly parsed.
I'm unsure if this is the correct way to fix this. This doesn't match with the typescript types from auth-js: https://github.com/supabase/auth-js/blob/a80f343abd133521faa07b90ccea15525b933238/src/lib/types.ts#L267 It contains `mfa/totp` which we aren't able to parse as well.
close #966
=> fix: Add magiclink as authenticaiton method in mfa

packages/gotrue/lib/src/gotrue_client.dart, packages/gotrue/test/client_test.dart
Bug fix
The `error_code` from the url response is ignored and not passed to the `AuthException`.
The `error_code` field is now set to `statusCode` from `AuthExcetption`.
close #964
=> fix: Add error_code from url to AuthException

packages/realtime_client/lib/src/realtime_channel.dart, packages/realtime_client/lib/src/realtime_client.dart, packages/realtime_client/lib/src/transformers.dart, packages/realtime_client/lib/src/types.dart, packages/realtime_client/test/channel_test.dart, packages/realtime_client/test/socket_test.dart, packages/realtime_client/test/transformers_test.dart
Adds support for authorization on broadcast and presence
Authorization is not supported on broadcast or presence allowing anyone to listen to its messages. 
Realtime channel created with `private: true` will respect RLS. Read more on the [official docs](https://supabase.com/docs/guides/realtime/authorization).
```dart
channel = supabase.channel(
'my_channel',
opts: const RealtimeChannelConfig(private: true),
);
```
Related JS PRs
- https://github.com/supabase/realtime-js/pull/408
- https://github.com/supabase/realtime-js/pull/414
=> feat(realtime_client): Add support for authorized realtime channels with broadcast and presence.

packages/supabase_flutter/lib/src/supabase_auth.dart
Fixing a bug where two `initialSession` is emitted. Also fixing a bug where deeplink isn't handled on the web.
Closes https://github.com/supabase/supabase-flutter/issues/937
Closes https://github.com/supabase/supabase-flutter/issues/974
=> fix(gotrue): Ensure a single `initialSession` is emitted.

packages/supabase/lib/src/auth_http_client.dart
This PR  properly handles null session and null `expiresAt` for a slim chance of them being null while making HTTP requests. 
Closes https://github.com/supabase/supabase-flutter/issues/969
=> fix: Add error messages for when the session or expiresAt was missing while making API requests. 

packages/functions_client/lib/functions_client.dart, packages/functions_client/lib/src/constants.dart, packages/functions_client/lib/src/functions_client.dart, packages/functions_client/test/custom_http_client.dart, packages/functions_client/test/functions_dart_test.dart
feature
The `body` can only be of type `Map<String,dynamic>` and no files can be uploaded.
The `body` can be any `Object`, which is encodable to String. There's now a `files` parameter to send files with a `MultipartRequest`.
At the moment everything is bundled in one method like in functions-js. One could argue to create an extra method to be more type safe with `body` being `Map<String,String>`.
close #933
=> feat: Support MultipartRequest in functions invoke

packages/functions_client/lib/src/types.dart
Add `toString` method to FunctionException so that the exception would show some context, hence making it easier to debug.
=> fix(functions_client): Add `toString` to `FunctionException`

CHANGELOG.md, packages/functions_client/CHANGELOG.md, packages/functions_client/lib/src/version.dart, packages/functions_client/pubspec.yaml, packages/supabase/CHANGELOG.md, packages/supabase/lib/src/version.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/CHANGELOG.md, packages/supabase_flutter/lib/src/version.dart, packages/supabase_flutter/pubspec.yaml
- functions_client@2.3.0
- supabase@2.2.6
- supabase_flutter@2.5.10
=> chore(release): Publish packages supabase_flutter@2.5.10

.github/workflows/functions_client.yml, .github/workflows/gotrue.yml, .github/workflows/postgrest.yml, .github/workflows/realtime_client.yml, .github/workflows/storage_client.yml, .github/workflows/supabase.yml, .github/workflows/supabase_flutter.yml, .github/workflows/yet_another_json_isolate.yml, melos.yaml, packages/supabase_flutter/example/pubspec.yaml, packages/yet_another_json_isolate/lib/src/_isolates_web.dart
Fixes an issue where the package is not able to build on Flutter web
Closes https://github.com/supabase/supabase-flutter/issues/989
=> fix: Make sure the package can be built on Flutter web

packages/functions_client/pubspec.yaml, packages/gotrue/lib/src/types/auth_exception.dart, packages/gotrue/lib/src/types/user_attributes.dart, packages/gotrue/pubspec.yaml, packages/postgrest/lib/src/postgrest_filter_builder.dart, packages/postgrest/pubspec.yaml, packages/realtime_client/pubspec.yaml, packages/realtime_client/test/socket_test_stubs.dart, packages/storage_client/lib/src/types.dart, packages/storage_client/pubspec.yaml, packages/supabase/lib/src/auth_user.dart, packages/supabase/lib/src/supabase_query_builder.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/example/pubspec.yaml, packages/supabase_flutter/pubspec.yaml, packages/supabase_flutter/test/widget_test_stubs.dart, packages/yet_another_json_isolate/pubspec.yaml
Upgrade the  `web_socket_channel` to `^3.0.1` which mostly serves as an upgrade path for the transitive `web` dependency which otherwise causes `web_socket_channel` to downgrade and prevent WASM support on the web platform.
When having `supabase` or `supabase_flutter` as a project dependeny while relying on `web: ^1.0.0` the  `web_socket_channel` dependeny would downgrade and WASM compilation isn't possible anymore.
This behavior seems to be migrated.
The breaking changes don't affect the codebase. Tests passed locally. Additionally, one linting error got fixed.
=> fix: Upgrade `web_socket_channel` for supporting `web: ^1.0.0` and therefore WASM compilation on web

packages/supabase/lib/src/auth_http_client.dart, packages/supabase/lib/src/supabase_client.dart, packages/supabase/test/client_test.dart, packages/supabase_flutter/lib/src/supabase.dart, packages/supabase_flutter/test/supabase_flutter_test.dart
Adds support for the accessToken option on the Supabase client which can be used to provide a third-party authentication (e.g. Auth0, Clerk, Firebase Auth, ...) access token or ID token to be used instead of Supabase Auth.
When set, supabase.auth.xyz cannot be used and an error will be thrown.
js PR here: https://github.com/supabase/supabase-js/pull/1004
=> feat: Add third-party auth support

packages/postgrest/lib/src/postgrest_builder.dart, packages/postgrest/lib/src/postgrest_filter_builder.dart, packages/postgrest/lib/src/postgrest_query_builder.dart, packages/postgrest/lib/src/postgrest_transform_builder.dart, packages/postgrest/lib/src/raw_postgrest_builder.dart, packages/postgrest/lib/src/response_postgrest_builder.dart, packages/postgrest/test/basic_test.dart, packages/postgrest/test/custom_http_client.dart
feature
To change the headers for one rpc or query call the instance wide headers objects needs to be changed.
After calling `.rpc` or `.from` individual header fields can be set with `.setHeader(key, value)`
js-pr: https://github.com/supabase/postgrest-js/pull/550
issue: #179
=> feat: Add setHeader method on postgrest builder

packages/supabase_flutter/test/supabase_flutter_test.dart
ci fix
Since app_links v6.2.0 the test is broken.
I remove the exact to check when app_links received the uri, because it highly depends on the version we are testing, since we still support old 3.5.0. Instead, I just way for 500ms, which should be enough.
The commit, which "broke" the test: https://github.com/llfbandit/app_links/commit/bb717cc91bc85dafad4ab4c55994fbb1b4094ea8
It's because the stream is now broadcast and doesn't emit the latest event when listening.
=> ci: Fix app_links test

README.md
docs update
No documentation on how to test the packages when contributing.
Add docs.
=> docs: Add package testing documentation to README

.github/workflows/functions_client.yml, .github/workflows/gotrue.yml, .github/workflows/postgrest.yml, .github/workflows/realtime_client.yml, .github/workflows/storage_client.yml, .github/workflows/supabase.yml, .github/workflows/supabase_flutter.yml, .github/workflows/yet_another_json_isolate.yml
ci update
We still use `checkout@v2`, which uses an old node version.
Upgrade to `checkout@v4` and remove the java checkout.
=> ci: Upgrade actions to remove deprecations

packages/realtime_client/lib/src/realtime_channel.dart, packages/realtime_client/lib/src/types.dart
Adds a realtime method to listen to system events for debugging purposes. 
JS PR: https://github.com/supabase/realtime-js/pull/422
Closes https://github.com/supabase/supabase-flutter/issues/1024
=> feat: Added onSystemEvents listener

packages/gotrue/lib/src/types/mfa.dart
Bug fix
Not all mfa auth methods can be parsed.
Add the rest of methods from [here](https://github.com/supabase/auth/blob/a6c18243b92b74798b6317e1c35c8a73bc3fd6e1/internal/models/factor.go#L54)
Just in case, is the auth team aware that the `MFAPhone` has different string values? :sweat_smile:
https://github.com/supabase/auth/blob/a6c18243b92b74798b6317e1c35c8a73bc3fd6e1/internal/models/factor.go#L81
and
https://github.com/supabase/auth/blob/a6c18243b92b74798b6317e1c35c8a73bc3fd6e1/internal/models/factor.go#L113
I have chosen `mfa/phone` for now.
#966
=> fix: Support all mfa auth methods

infra/storage_client/docker-compose.yml, infra/storage_client/postgres/Dockerfile, infra/storage_client/postgres/storage-schema.sql, infra/storage_client/storage/Dockerfile, packages/storage_client/lib/src/storage_file_api.dart, packages/storage_client/test/client_test.dart
feature
The option to copy/move to a different bucket is missing.
Add the missing option.
close #1034
=> feat(storage_client): Support copy/move to different bucket

packages/realtime_client/lib/realtime_client.dart, packages/realtime_client/lib/src/constants.dart, packages/realtime_client/lib/src/realtime_channel.dart, packages/realtime_client/lib/src/realtime_client.dart, packages/realtime_client/test/mock_test.dart, packages/realtime_client/test/socket_test.dart, packages/supabase/lib/src/supabase_query_builder.dart, packages/supabase/lib/src/supabase_stream_builder.dart, packages/supabase/test/mock_test.dart, packages/supabase_flutter/lib/src/supabase.dart, packages/supabase_flutter/lib/src/supabase_auth.dart
Bug fix
The behavior of the app in background depends on the platform, but by always stopping the access token refreshing, the realtime connection may keep an invalid access token and therefore the connection get closed by server. When the realtime connection gets interrupted, it gets automatically reconnected as long as it never sent some expired access token.
~~When a realtime channel is open, the access token keeps refreshing while the app is in background.~~
In addition, I did more management to keep realtiem and postgrest in sync for the stream method. If the postgrest request fails, I unsubscribe the realtime connection and close the stream as I see no benefit in leaving it open, as it would just be a realtime connection by then. The dev using the stream method should handle such …
=> fix: Better stream and access token management

packages/yet_another_json_isolate/CHANGELOG.md, packages/yet_another_json_isolate/lib/yet_another_json_isolate.dart
Fix
- closes #1047 
- see Issue for more detailed information.
`Supabase.initialize()` doesn't work correctly on Dart 3.5+ with WASM Compiler
`Supabase.initialize()` works!
- https://github.com/supabase-community/json-isolate-dart/pull/7
=> fix(yet_another_json_isolate): Conditional export now works correctly with Dart 3.5+

packages/functions_client/lib/src/functions_client.dart, packages/functions_client/pubspec.yaml, packages/gotrue/lib/src/broadcast_web.dart, packages/gotrue/lib/src/gotrue_client.dart, packages/gotrue/pubspec.yaml, packages/postgrest/lib/src/postgrest.dart, packages/postgrest/lib/src/postgrest_builder.dart, packages/postgrest/pubspec.yaml, packages/realtime_client/lib/src/realtime_client.dart, packages/realtime_client/pubspec.yaml, packages/storage_client/lib/src/fetch.dart, packages/storage_client/lib/src/storage_client.dart, packages/storage_client/pubspec.yaml, packages/supabase/lib/src/auth_user.dart, packages/supabase/lib/src/remove_subscription_result.dart, packages/supabase/lib/src/supabase_client.dart, packages/supabase/lib/src/supabase_event_types.dart, packages/supabase/lib/src/supabase_realtime_error.dart, packages/supabase/lib/src/supabase_stream_builder.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/README.md, packages/supabase_flutter/lib/src/supabase.dart, packages/supabase_flutter/lib/src/supabase_auth.dart, packages/supabase_flutter/pubspec.yaml
feature
When debugging the auth broadcasting or the realtime/stream fixed I had to manually add many print statements, which was annoying. The js sdk already has some logging.
Add logging via the [logging](https://pub.dev/packages/logging) package from dart.dev. This primarily only tracks the logs. When `debug` is true in the supabase_flutter `Supabase` instance, records with level `INFO` or higher are printed.
The logger instances are laid in a hierarchy separated by dots, which allows all supabase loggers to be united in a `supabase` logger instance.
=> feat: Add logging

packages/gotrue/lib/src/broadcast_web.dart, packages/gotrue/lib/src/gotrue_client.dart, packages/supabase_flutter/README.md
Bug fix
The logger from the gotrue package is named `supabase.gotrue`
Renamed the logger from the gotrue package to `supabase.auth`
I've missed pushing this commit in #1042
=> fix: Rename logger from gotrue to auth

CHANGELOG.md, packages/functions_client/CHANGELOG.md, packages/functions_client/lib/src/version.dart, packages/functions_client/pubspec.yaml, packages/gotrue/CHANGELOG.md, packages/gotrue/lib/src/version.dart, packages/gotrue/pubspec.yaml, packages/postgrest/CHANGELOG.md, packages/postgrest/lib/src/version.dart, packages/postgrest/pubspec.yaml, packages/realtime_client/CHANGELOG.md, packages/realtime_client/lib/src/version.dart, packages/realtime_client/pubspec.yaml, packages/storage_client/CHANGELOG.md, packages/storage_client/lib/src/version.dart, packages/storage_client/pubspec.yaml, packages/supabase/CHANGELOG.md, packages/supabase/lib/src/version.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/CHANGELOG.md, packages/supabase_flutter/example/pubspec.yaml, packages/supabase_flutter/lib/src/version.dart, packages/supabase_flutter/pubspec.yaml
- functions_client@2.4.0
- gotrue@2.10.0
- postgrest@2.3.0
- realtime_client@2.4.0
- storage_client@2.2.0
- supabase@2.5.0
- supabase_flutter@2.8.0
=> chore(release): Publish packages supabase_flutter@2.8.0

packages/gotrue/lib/src/gotrue_admin_api.dart
This fix sends metadata when using `inviteUserByEmail()`
- Bug fix
When using the `inviteUserByEmail()` function, the `user_metadata` field remains empty, even when data is provided.
**Relevant Issue:**  
[Issue #1059](https://github.com/supabase/supabase-flutter/issues/1059)
The `inviteUserByEmail()` function now successfully sends user metadata when provided. The `user_metadata` field will correctly include the submitted data.
This change ensures that any metadata passed during the invitation process is included in the request.
```dart
final UserResponse res = await supabase.client.auth.admin.inviteUserByEmail(
'test@test.com',
data: {
'first_name': "test",
'last_name': "one",
},
);
=> fix: Send metadata inviteUserByEmail()

packages/gotrue/lib/src/types/types.dart
Fix
Trying to pass OAuthProvider.slack to sign in will set the `provider` url parameter value to `"slack"`, though `"slack_oidc"` is needed to authenticate properly with Slack OIDC authentication option.
You're able to pass `OAuthProvider.slackOidc` giving you the correct url param in the authentication request url.
Gotrue exported `OAuthProvider` doesn't currently include Slack OIDC provider option.
I had this verified by Supabase support when trying to figure out what was wrong with my auth setup (big thanks to Jenny Kibiri)
=> fix: Updated gotrue types.dart to include slackOidc

packages/gotrue/lib/src/gotrue_client.dart
Relate: https://github.com/supabase/supabase-flutter/issues/1045
Add Keycloak Provider on signInWithIdToken
signInWithIdToken are only available for Google, Apple or Kakao
Authorize Keycloak to use signInWithIdToken
We need a transparent connection that uses the accessToken and idToken that provides us with keycloak authentication.
As the connection has already been established through our systems, we need to provide the authentication information to gotrue directly using the signInWithIdToken method.
=> feat: Add Keycloak Provider on signInWithIdToken

packages/gotrue/lib/src/types/user_attributes.dart, packages/gotrue/test/src/types/user_attributes_test.dart
Fix both `UserAttributes` and `AdminUserAttributes` classes by adding equality.
```dart
final attributeOne = UserAttributes(password: newPassword);
final attributeTwo = UserAttributes(password: newPassword);
attributeOne == attributeTwo // false
```
```dart
final attributeOne = UserAttributes(password: newPassword);
final attributeTwo = UserAttributes(password: newPassword);
attributeOne == attributeTwo // true
```
Encountered this behaviour when I tried to verify if my mock was called with the right values.
```dart
verify(() => mockAuthClient.updateUser(supa.UserAttributes(password: newPassword))); // failed
``` 
I then added the equality to the class in my pub cache and it worked.
=> fix: Add equality to user attributes classes

infra/postgrest/db/00-schema.sql, packages/postgrest/lib/src/postgrest.dart, packages/postgrest/lib/src/postgrest_builder.dart, packages/postgrest/lib/src/postgrest_filter_builder.dart, packages/postgrest/lib/src/postgrest_rpc_builder.dart, packages/postgrest/test/basic_test.dart, packages/postgrest/test/custom_http_client.dart, packages/postgrest/test/reset_helper.dart, packages/supabase/lib/src/supabase_client.dart, packages/supabase/lib/src/supabase_query_schema.dart
feature
The `get` parameter for read-only access mode for rpc is not supported.
It's supported.
[js-doc](https://supabase.com/docs/reference/javascript/rpc)
close #1075
=> feat: Read-only access mode rpc

packages/supabase/lib/src/supabase_client.dart, packages/supabase_flutter/lib/src/supabase.dart, packages/supabase_flutter/lib/src/supabase_auth.dart, packages/supabase_flutter/test/supabase_flutter_test.dart
Bug fix
Passing a custom access token to supabase_flutter doesn't work. I noticed that the `SupabaseClient.dispose()` method didn't work with custom access token as well.
The realtime reconnection logic is moved to the `Supabase` class and `SupabaseAuth` is only initialized when no custom `accessToken` is passed.
close #1072
=> fix: Support custom access token

packages/supabase/lib/src/supabase_stream_builder.dart, packages/supabase/test/mock_test.dart
Bundles the three separate Postgres change listener within Stream into a single `PostgresChangeEvent.all` subscription, which helps reduce the number of subscriptions opened on the database for every single time `.stream()` is called.
=> fix(realtime_client): Consolidate realtime subscription for stream

packages/gotrue/lib/src/gotrue_client.dart
[Supabase Docs](https://supabase.com/docs/guides/auth/auth-email-passwordless?queryGroups=language&language=dart#with-magic-link
)
Following the above link, verifying token hash from magic link doesn't require email or phone in request body
(only 'token hash' and 'type' is required in the js example)
Pre commit state of the code threw assertion error if neither email nor phone is present in verifyOtp call preventing users to verify token hash without passing email or phone in request body ("auth/verify" endpoint called inside this function throws an error as well if email or phone is passed in request body along with token hash and type)
Hence have added a condition that will ignore the first email and phone assertion if token hash is populate
=> fix: Ignore email and phone assertions when token hash is being verified

packages/postgrest/lib/src/postgrest.dart
Docs update.
Typo on RPC function docs where the current docs says:
```
/// [params] is an optinal object to pass as arguments to the function call.
```
Typo on RPC function docs where the current docs says:
```
/// [params] is an optional object to pass as arguments to the function call.
```
=> docs: Fix typo for RPC docs

packages/supabase_flutter/pubspec.yaml
Mark in the pubspec.yaml of the supabase_flutter package that the linux platform is supported. This was previously not marked as supported, because of missing deeplink support, with an update to the app_links package this got resolved.
#278
=> chore(supabase_flutter): State that linux is supported

packages/functions_client/lib/src/functions_client.dart, packages/storage_client/lib/src/storage_client.dart, packages/supabase/lib/src/realtime_client_options.dart, packages/supabase_flutter/lib/src/supabase.dart
=> docs: Fix typos

packages/supabase/lib/src/supabase_client.dart, packages/supabase_flutter/lib/src/supabase.dart
Bug fix. 
Currently `null` cannot be returned from `accessToken` function. 
`null` can be returned from `accessToken` when the user on the third-party auth is not signed in.
Related https://github.com/supabase/supabase-js/pull/1332
=> fix: Allow null to be returned from accessToken function when the user is not signed in

.github/workflows/coverage.yml, .github/workflows/functions_client.yml, .github/workflows/gotrue.yml, .github/workflows/postgrest.yml, .github/workflows/realtime_client.yml, .github/workflows/storage_client.yml, .github/workflows/supabase.yml, .github/workflows/supabase_flutter.yml, .github/workflows/yet_another_json_isolate.yml, melos.yaml, packages/realtime_client/lib/src/realtime_client.dart, packages/realtime_client/test/socket_test.dart
Generate coverage reports for each package and upload them.
A new GitHub actions workflow file, `coverage.yml` is introduced, which runs the test for all the packages, generates coverage reports, combines them, and uploads them. This test is redundant as the tests are also run in each individual CI pipeline, but after struggling a bit trying to combine the coverage reports from multiple different workflows, I settled with this implementation.
This PR also includes minor type fix and test stub fix in the realtime rep.
=> chore: Generate coverage reports and upload them.

packages/realtime_client/lib/src/constants.dart, packages/realtime_client/lib/src/realtime_client.dart, packages/realtime_client/test/socket_test.dart
Heartbeat interval is 30s
Change heartbeat interval to 25s
The change on heartbeat stems from what we've seen from user feedback that 30s might hit the limits of socket connections and we end up with a weird timing issue where the socket gets closed just as we are sending heartbeat.
=> fix(realtime): Lower heartbeat interval to 25s

packages/yet_another_json_isolate/lib/src/_isolates_io.dart, packages/yet_another_json_isolate/lib/src/_isolates_web.dart
This is a new feature for `YAJsonIsolate`.
In testing environments, it's easy to have multiple clients open. Specifically, I usually have an admin client and a client for the current user, but I can't tell which is which because all isolates have the same name. When an error occurs in the isolate, it takes a lot of effort to figure out which client produced it.
I would like to be able to rename isolates, specifically for use in debugging.
Currently, all isolates spawned have the name `_compute`.
Here's a screenshot of what it looks like in VSCode.
There's now a `debugName` constructor parameter on `YAJsonIsolate`. The user can add the library to their package and instantiate an instance with their desired `debugName` if they want to access it. 
Here's a screenshot of what it looks like in …
=> feat: Add debugName parameter to YAJsonIsolate.

packages/functions_client/lib/src/types.dart
`FunctionException` should implement `Exception`
close #1127
=> fix: FunctionException implements Exception

.github/workflows/supabase_flutter.yml, packages/gotrue/lib/src/broadcast_web.dart, packages/gotrue/lib/src/gotrue_client.dart, packages/gotrue/lib/src/types/auth_state.dart, packages/gotrue/pubspec.yaml, packages/gotrue/test/src/broadcast_web_test.dart, packages/realtime_client/lib/src/websocket/websocket.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/lib/src/local_storage.dart, packages/supabase_flutter/pubspec.yaml
This PR [migrates gotrue to package:web](https://dart.dev/interop/js-interop/package-web).
Because of version constraints issues, this bumps the minimum Dart version to 3.3.0 and Flutter version to 3.19.0, which has been released in Feb 16, 2024.
Uses the old html API, which causes analysis issue, and is not recommended to keep by the Flutter team.
The new web package is used.
=> feat(gotrue, supabase, supabase_flutter, realtime_client): Use web package to access web APIs

packages/gotrue/lib/src/fetch.dart, packages/gotrue/lib/src/gotrue_client.dart, packages/gotrue/lib/src/types/auth_exception.dart, packages/gotrue/lib/src/types/auth_state.dart, packages/gotrue/test/client_test.dart, packages/gotrue/test/custom_http_client.dart
Bug fix
When receiving an error response, which doesn't contain any body, the decoding to json throws a `FormatException`. This is very misleading, because we shouldn't try to decode an empty response. This happened to me while doing some testing, but I do not exactly remember the reason for the error anymore.
Do not decode an empty response.
In addition, I added a `toString` for every subclass of `AuthException`.
=> fix(gotrue): Handle empty error response

.github/workflows/coverage.yml, .github/workflows/functions_client.yml, .github/workflows/gotrue.yml, .github/workflows/postgrest.yml, .github/workflows/realtime_client.yml, .github/workflows/storage_client.yml, .github/workflows/supabase.yml, .github/workflows/supabase_flutter.yml, .github/workflows/title-validation.yml, .github/workflows/yet_another_json_isolate.yml
revoke pull_request_target and explicit permissions
=> ci: Explicit permissions on actions

packages/gotrue/lib/src/types/auth_exception.dart
I was a little bit confused by the logs because the AuthException doesn't contain a variable `errorCode`.
The `toString` output is not aligned with the variable name
The `toString` output is aligned with the variable name
_None_
=> fix(gotrue): AuthException .toString method

CHANGELOG.md, packages/functions_client/CHANGELOG.md, packages/functions_client/lib/src/version.dart, packages/functions_client/pubspec.yaml, packages/gotrue/CHANGELOG.md, packages/gotrue/lib/src/version.dart, packages/gotrue/pubspec.yaml, packages/postgrest/CHANGELOG.md, packages/postgrest/lib/src/version.dart, packages/postgrest/pubspec.yaml, packages/realtime_client/CHANGELOG.md, packages/realtime_client/lib/src/version.dart, packages/realtime_client/pubspec.yaml, packages/storage_client/CHANGELOG.md, packages/storage_client/lib/src/version.dart, packages/storage_client/pubspec.yaml, packages/supabase/CHANGELOG.md, packages/supabase/lib/src/version.dart, packages/supabase/pubspec.yaml, packages/supabase_flutter/CHANGELOG.md, packages/supabase_flutter/example/pubspec.yaml, packages/supabase_flutter/lib/src/version.dart, packages/supabase_flutter/pubspec.yaml, packages/yet_another_json_isolate/CHANGELOG.md, packages/yet_another_json_isolate/pubspec.yaml
- functions_client@2.4.2
- gotrue@2.12.0
- realtime_client@2.5.0
- storage_client@2.4.0
- supabase@2.7.0
- supabase_flutter@2.9.0
- yet_another_json_isolate@2.1.0
- postgrest@2.4.2
=> chore(release): Publish packages supabase_flutter@2.9.0

packages/supabase/lib/src/constants.dart, packages/supabase/test/client_test.dart
Bug fix, feature, docs update, ...
Please link any relevant issues here.
Feel free to include screenshots if it includes visual changes.
=> feat: Add standard client headers

packages/realtime_client/lib/src/realtime_client.dart, packages/realtime_client/test/socket_test.dart
- Remove the jwt check when pushing access token
- On set auth, also send the client info for better internal reports.
https://github.com/supabase/realtime-js/pull/451
https://github.com/supabase/realtime-js/pull/455
=> fix(realtime): Send version when joining channel and remove jwt check

packages/gotrue/lib/src/gotrue_admin_api.dart, packages/gotrue/lib/src/gotrue_admin_mfa_api.dart, packages/gotrue/lib/src/helper.dart, packages/gotrue/test/admin_test.dart
Fix https://github.com/supabase/supabase-flutter/issues/1170
Admin methods currently accept ids of any format
Admin methods now validates if id is a uuid
=> fix(auth): Validate uuid params in admin methods

packages/gotrue/lib/src/gotrue_client.dart
Refactor
_currentUser variable is just being stored as a copy of _currentSession.user
The currentUser getter is handling the indirection correctly, no need to duplicate values and assign both each time they change.
I have simplified a comment (it was a double negation).
I have added some bang operators in cases where null-aware operator where not needed
=> refactor(gotrue): Remove unused _currentUser field and update currentUser getter logic. 

packages/functions_client/lib/src/functions_client.dart, packages/functions_client/test/custom_http_client.dart, packages/functions_client/test/functions_dart_test.dart
Currently, calling a function that returns a binary isn't properly handled by the function. This PR fixes that and adds a bunch of test cases to improve coverage.
=> fix(functions_client): Handle binary data request properly and improve test coverage

infra/gotrue/docker-compose.yml, packages/gotrue/lib/src/gotrue_mfa_api.dart, packages/gotrue/lib/src/types/mfa.dart, packages/gotrue/test/src/gotrue_mfa_api_test.dart
feature of adding phone support for MFA enrollment
JS PR here: https://github.com/supabase/auth-js/pull/932
Enrolling in MFA via SMS is supported .
SMS MFA is not supported.
=> feat(gotrue): Add phone mfa enrollment

packages/supabase/test/client_test.dart, packages/supabase/test/mock_test.dart, packages/supabase/test/utilities_test.dart
No package code change. Just adding more tests for better coverage.
=> chore(supabase): Improve test coverage for supabase

packages/supabase_flutter/lib/src/supabase.dart
This PR introduces a minor update to the `initialize()` method to avoid throwing when called multiple times. Instead, it logs an informational message and returns the existing instance, making initialization idempotent and smoother for production use.
- Replaced `assert(!_instance.isInitialized)` with a runtime check to prevent throwing.
- Added `_log.info()` when a reinitialization attempt occurs.
- Exposed `isInitialized` as a public read-only getter for improved observability.
- Avoids throwing errors in release mode by gracefully handling repeated initialization.
Closes https://github.com/supabase/supabase-flutter/issues/1163
=> feat(supabase_flutter): Make `Supabase.initialize()` idempotent

packages/realtime_client/lib/src/realtime_client.dart, packages/realtime_client/test/socket_test.dart, packages/supabase_flutter/lib/src/supabase.dart
Bug fix
After app changes its life cycle, `onResumed()` method is called to resume any open web socket connection. This code is executed 
```
if (realtime.channels.isNotEmpty) {
if (realtime.connState == SocketStates.disconnecting) {
bool cancel = false;
final connectFuture = realtime.conn!.sink.done.then(
```
So, if the `SocketStates` is `disconnecting` it will try to use `realtime.conn!` assuming is not `null` when it can be `null`, hence throwing an error **Null check operator used on a null value**
If we look inside `RealtimeClient` which holds `conn` and `connState` we can see the only time `conn` is set to `null` and the only time `connState` is set to `SocketStates.disconnection` is here, in the `disconnect` method
```
Future<void> disconnect({int? code, String? reason}) async { …
```
=> fix(supabase_flutter): Safely check if conn is not null to avoid null check operator

packages/gotrue/lib/src/gotrue_client.dart
Feature - This PR adds a new linkIdentityWithIdToken method to the GoTrue client for linking identities using ID tokens, and refactors the existing signInWithIdToken method to share common code.
Currently, users can only sign in with ID tokens using the signInWithIdToken method, but there's no way to link additional identities to an existing user account using ID tokens. The signInWithIdToken and any potential identity linking methods would have duplicate code.
- New Method: Added linkIdentityWithIdToken method that allows linking identities to existing users using ID tokens
- Code Refactoring: Extracted common logic into _signInWithIdToken helper method to eliminate code duplication
- Backward Compatibility: signInWithIdToken maintains the exact same API and behavior
- Shared Logic: Both …
=> feat(gotrue): Implement `linkIdentityWithIdToken` method
